### ISSUE TITLE
Unable to reach a settlement: issue :(

### ISSUE THREAD

**Issue by chezn** [hierynomus/sshj#121]
Getting below error when I try to run a command.
code used:
                 client.connect(targetHost);
		client.authPassword(userName, password);
	         session = client.startSession();;
		cmd = session.exec(command);
		cmd.join(wait, TimeUnit.SECONDS);
                InputStream in = cmd.getInputStream();

14:08:04,912 ERROR [net.schmizz.concurrent.Promise] (Thread-504) <<kex done>> woke to: net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [] and [aes128-ctr, aes128-cbc, arcfour, 3des-cbc, blowfish-cbc, aes192-ctr, aes192-cbc, aes256-ctr, aes256-cbc]
TransportException exception occurredUnable to reach a settlement: [] and [aes128-ctr, aes128-cbc, arcfour, 3des-cbc, blowfish-cbc, aes192-ctr, aes192-cbc, aes256-ctr, aes256-cbc]
 Unable to reach a settlement: [] and [aes128-ctr, aes128-cbc, arcfour, 3des-cbc, blowfish-cbc, aes192-ctr, aes192-cbc, aes256-ctr, aes256-cbc]: net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [] and [aes128-ctr, aes128-cbc, arcfour, 3des-cbc, blowfish-cbc, aes192-ctr, aes192-cbc, aes256-ctr, aes256-cbc]
        at net.schmizz.sshj.transport.Proposal.firstMatch(Proposal.java:165) [sshj-0.9.0.jar:]
        at net.schmizz.sshj.transport.Proposal.negotiate(Proposal.java:147) [sshj-0.9.0.jar:]
        at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:239) [sshj-0.9.0.jar:]
        at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:364) [sshj-0.9.0.jar:]
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:478) [sshj-0.9.0.jar:]
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:127) [sshj-0.9.0.jar:]
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:195) [sshj-0.9.0.jar:]
        at net.schmizz.sshj.transport.Reader.run(Reader.java:72) [sshj-0.9.0.jar:]

**Comment by hierynomus** [comment]
You need to use high strength ciphers probably. Download the JCE (Java Cryptography Extensions) and try again...

**Comment by hierynomus** [comment]
@chezn Is this isue still active? If so, could you try loading the JCE extensions and then try again. Else could you let me know whether I can close hte issue?

**Comment by hierynomus** [comment]
Closing this issue due to inactivity. Workaround should be to load the JCE extensions.
