### ISSUE TITLE
Writing more than 2^15 causes Exception, more than 2^21 bytes of data at once causes hang

### ISSUE THREAD

**Issue by jchien14** [hierynomus/sshj#145]
If I try to write 32768 bytes of data or once or more, I get the follow error:

<pre>
net.schmizz.sshj.sftp.SFTPException: EOF while reading packet
    at net.schmizz.sshj.sftp.PacketReader.readIntoBuffer(PacketReader.java:52)
    at net.schmizz.sshj.sftp.PacketReader.getPacketLength(PacketReader.java:57)
    at net.schmizz.sshj.sftp.PacketReader.readPacket(PacketReader.java:73)
    at net.schmizz.sshj.sftp.PacketReader.run(PacketReader.java:85)
    Suppressed: net.schmizz.sshj.connection.ConnectionException: Stream closed
        at net.schmizz.sshj.connection.channel.ChannelOutputStream.checkClose(ChannelOutputStream.java:178)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:159)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:153)
        at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:269)
        at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:124)
        at net.schmizz.sshj.sftp.RemoteResource.close(RemoteResource.java:53)
                ...
</pre>

If I try to write more than 2^21 bytes at once, in SFTP.transmit(), remoteWindowSize becomes 0, causing it to call win.awaitExpansion(), which hangs forever right now as I don't think it ever sends a request to increase the window size. 

Tested with 0.9.0 against OpenSSH

**Comment by fakemail324** [comment]
Hi,
We stared using SSHJ as a replacement for Jsch in our project and recently we started facing the "deadlock" issue. Are there any plans to fix it?

Regards

**Comment by billstephens** [comment]
I'm trying to optimize performance for buffered writes to our Linux SFTP server for a unhappy customer. I've been testing a variety of buffer sizes and ran into this. I was totally not understanding why I was getting these errors for buffer sizes > 2^15.

**Comment by jgoldverg** [comment]
When will this bug be fixed? I currently am being throttled very heavily as when I am trying to send a 50GB+ file I am unable to use an appropriate chunk size aside from 32KB as said above.

**Comment by sfromis** [comment]
While I have no way around the 32KB max chunk size, I've found that speed got better by including a max unconfirmed reads/writes parameter of 1 when creating the stream for the remote file. Maybe a higher value can be useful, depending on the risk of network latency.
