### ISSUE TITLE
Connecting with 8 concurrent connections already causes a TransportException

### ISSUE THREAD

**Issue by jchien14** [hierynomus/sshj#147]
Haven't investigated too much so this may not be a bug but even if the Server accepts more than 8 concurrent connections, I get the following exception when trying to open up a 9th concurrent connection:

Calling SshClient.connect with 8 concurrent connections already causes a Connection reset
net.schmizz.sshj.transport.TransportException: Connection reset
  at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:165)
  at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:683)
  at net.schmizz.sshj.SocketClient.connect(SocketClient.java:71)
  at net.schmizz.sshj.SocketClient.connect(SocketClient.java:77)
  ...
Caused by: java.net.SocketException: Connection reset
  at java.net.SocketInputStream.read(SocketInputStream.java:196)
  at java.net.SocketInputStream.read(SocketInputStream.java:122)
  at java.net.SocketInputStream.read(SocketInputStream.java:210)
  at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:159)
  ... 14 more

**Comment by hierynomus** [comment]
Can you provide with a unit test that shows the problem?

**Comment by hierynomus** [comment]
@jchien14 Can you provide a test-case that exhibits this behaviour?
