### ISSUE TITLE
RSA public key exchange not working

### ISSUE THREAD

**Issue by harschware** [hierynomus/sshj#159]
I'm trying to trace down an issue I found with Scala SSH (http://stackoverflow.com/questions/27067499/scala-ssh-connecting-to-hosts-with-public-key-exchange)
which I think boils down to the issue that RSA public key exchange does not seem to work in SSHJ.  
Using this snippet:
https://gist.github.com/harschware/056200934ffdc7fa8242

I was able to connect to my server when it had a DSA key pair, but when I changed it to use an RSA key it would give me the following error:

Exception in thread "main" net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
    at net.schmizz.sshj.SSHClient.auth(SSHClient.java:217)
    at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:316)
    at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:365)
    at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:295)
    at harschware.sandbox.SSHJConnet.main(SSHJConnet.java:27)
Caused by: net.schmizz.sshj.userauth.UserAuthException: Problem getting private key from PKCS8KeyFile{resource=[PrivateKeyFileResource] /Users/tharsch/.ssh/id_rsa}
    at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putSig(KeyedAuthMethod.java:61)
    at net.schmizz.sshj.userauth.method.AuthPublickey.sendSignedReq(AuthPublickey.java:74)
    at net.schmizz.sshj.userauth.method.AuthPublickey.handle(AuthPublickey.java:45)
    at net.schmizz.sshj.userauth.UserAuthImpl.handle(UserAuthImpl.java:136)
    at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:455)
    at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:107)
    at net.schmizz.sshj.transport.Decoder.received(Decoder.java:175)
    at net.schmizz.sshj.transport.Reader.run(Reader.java:61)
Caused by: org.bouncycastle.openssl.PasswordException: Password is null, but a password is required
    at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
    at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
    at net.schmizz.sshj.userauth.keyprovider.PKCS8KeyFile.readKeyPair(PKCS8KeyFile.java:143)
    at net.schmizz.sshj.userauth.keyprovider.PKCS8KeyFile.getPrivate(PKCS8KeyFile.java:72)
    at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putSig(KeyedAuthMethod.java:59)
    ... 7 more

**Comment by hierynomus** [comment]
Is your private key protected by a passphrase?

**Comment by harschware** [comment]
No.  It was not.  Same can be said for both rsa and dsa on that system.  Would this be a requirement for both?  Strange it would try to enforce that, and stranger it wouldn't use the term 'passphrase' which might have helped my tired eyes.

**Comment by hierynomus** [comment]
I would need to debug this some more... Could you write a unit test with
sample data?

**Comment by hierynomus** [comment]
Looking at the code, it deduces that your keypair is a `PEMEncryptedKeyPair` instead of a `PEMKeyPair`. This is determined by the header in the `id_rsa` file, which would be in your case `-----BEGIN ENCRYPTED PRIVATE KEY-----`.

Could you send a sample key and a command line how you generated your RSA key?

**Comment by harschware** [comment]
I usually follow these instructions: http://archive.oreilly.com/pub/h/66

So,
% ssh-keygen -t rsa

with empty passphrases.

**Comment by ktham** [comment]
I'm also facing the same issue. Is there anyone that can confirm that can successfully use their id_rsa file with sshj? I also use an empty passphrase

**Comment by ktham** [comment]
Ah, nevermind, it was a different issue (with scala-ssh). I got it to work. thanks

**Comment by dkocher** [comment]
This issue can be closed it seems.

**Comment by hierynomus** [comment]
@dkocher No, Tim's (@harschware) problem does exist unfortunately.

**Comment by johnscancella** [comment]
Is there any work around for this? I am running into the same problem.

**Comment by hierynomus** [comment]
Hi @johnscancella,

Are you getting exactly the same problem as @harschware initially had?
How did you generate your key?

**Comment by johnscancella** [comment]
Not exactly. I can scp a file if I provide a username and password, but if I use my RSA key it doesn't work. I generated it using the instructions from github
https://help.github.com/articles/generating-ssh-keys/
I also use this key to auto login(no password prompt) when connecting via ssh.

**Comment by hierynomus** [comment]
Can you send me the stacktrace you get and the header (first line) of the private key file (i.e. the part between the `----`). Also what is the code you're using with SSHJ?

**Comment by johnscancella** [comment]
I think it may be due to the key I was using. I generated another key specifying ssh2 and that seems to work.

**Comment by hierynomus** [comment]
Glad you got it to work @johnscancella. Would still be interesting to know what the problem was with the previous key you had. Would you mind still sharing the requested details (or provide a unit test with the associated key) :)

**Comment by johnscancella** [comment]
I don't have the stack trace anymore as I ended up using Apache Ant instead. Here is the header of the ssh key:
> -----BEGIN RSA PRIVATE KEY-----
> Proc-Type: 4,ENCRYPTED
> DEK-Info: AES-128-CBC,A2F48D7249798F23F5B5DD1FBAF1E430

I based the code off of the upload example found here
https://github.com/hierynomus/sshj/blob/master/examples/src/main/java/net/schmizz/sshj/examples/SCPUpload.java

**Comment by pnwguy** [comment]
I am hitting same issue as @johnscancella.  I have same type of RSA private key, I do have passphrase, and my code looks just like the one in SCPUpload.java.  Here's call stack:

net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:114)
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:205)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:305)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:353)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:283)
	at ...
	at ...
Caused by: net.schmizz.sshj.userauth.UserAuthException: Problem getting private key from PKCS8KeyFile{resource=[PrivateKeyFileResource] /Users/gyvkof/.ssh/id_rsa}
	at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putSig(KeyedAuthMethod.java:61)
	at net.schmizz.sshj.userauth.method.AuthPublickey.sendSignedReq(AuthPublickey.java:74)
	at net.schmizz.sshj.userauth.method.AuthPublickey.handle(AuthPublickey.java:45)
	at net.schmizz.sshj.userauth.UserAuthImpl.handle(UserAuthImpl.java:165)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:474)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:127)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:195)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:72)
Caused by: org.bouncycastle.openssl.PasswordException: No password finder specified, but a password is required
	at org.bouncycastle.openssl.PEMReader$KeyPairParser.readKeyPair(Unknown Source)
	at org.bouncycastle.openssl.PEMReader$RSAKeyPairParser.parseObject(Unknown Source)
	at org.bouncycastle.openssl.PEMReader.readObject(Unknown Source)
	at net.schmizz.sshj.userauth.keyprovider.PKCS8KeyFile.readKeyPair(PKCS8KeyFile.java:129)
	at net.schmizz.sshj.userauth.keyprovider.PKCS8KeyFile.getPrivate(PKCS8KeyFile.java:66)
	at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putSig(KeyedAuthMethod.java:59)
	... 7 more

**Comment by hierynomus** [comment]
@pnwguy If you generate a key with a passphrase, be sure to use the `SSHClient.loadKeys` method and ensure that you pass either a `PasswordFinder`, or the passphrase.

**Comment by pnwguy** [comment]
Oh snap, my bad, thanks!

**Comment by bernardbezzina** [comment]
Hi I'm running into a similar problem, I've generated a key with a passphrase and have this simple javacode:

        SSHClient ssh = new SSHClient();
        ssh.addHostKeyVerifier(new PromiscuousVerifier());
        ssh.connect(hostname);

        File keyFile = new File(privateKeyLocation);
        FileKeyProvider keyProvider = new PKCS8KeyFile();
        keyProvider.init(keyFile);

        ssh.loadKeys(keyFile.toString(), PasswordUtils.createOneOff(passphrase.toCharArray()));
        ssh.authPublickey(username);
		
        Session session = ssh.startSession();
        session.exec(command);

and I get this stacktrace:

        Root Exception stack trace:
        net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:217)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:316)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:365)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:295)

Passphrase seems to be authenticated fine with the key because when I change it I get a different exception (that the password is null or incorrect). So why this exception??

**Comment by bernardbezzina** [comment]
Ignore my previous post, I had authorized_keys missing from my server. Resolved now :)

**Comment by hierynomus** [comment]
Ok, great!

2015-11-05 12:21 GMT+01:00 bernardbezzina <notifications@github.com>:

**Comment by stefan-reich** [comment]
Hi guys... I think I have the same problem. This is on Linux (client+server). I can do "ssh root@tinybrain.de" without a password, so it is all set up (~/.ssh/id_rsa exists).

I can use sshj WITH password: http://tinybrain.de/1003580

But I can't use sshj without password: http://tinybrain.de/1004830

net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:217)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:316)

Any ideas?

I'm trying to turn on slf4j logging...

**Comment by johnscancella** [comment]
@stefan-reich slf4j is just a bunch of interfaces, to change the logging you would have to find out which logging system it is actually using (log4j, logback, etc) and follow their instructions for changing the logging.

**Comment by hierynomus** [comment]
@stefan-reich Just the exception trace doesn't really help to debug this. You really need to provide some (debug level) logging to know what's going on here.
