### ISSUE TITLE
sftp does not resolve the env var in the file path

### ISSUE THREAD

**Issue by missedone** [hierynomus/sshj#174]
Hi folks

i use sshj sftpclient to upload the file to a linux box, but the test case failed if the remote file path contains env var, e.g. "$HOME/a.txt" below:
```
	@Test
	public void testUpload() throws Exception {
		try (SSHClient ssh = new SSHClient()) {
            ssh.setConnectTimeout(60 * 1000);
            ssh.setTimeout(60 * 60 * 1000);
            ssh.getConnection().getKeepAlive().setKeepAliveInterval(30);
            ssh.loadKnownHosts();
            ssh.addHostKeyVerifier(new PromiscuousVerifier());

            ssh.connect(host);
            ssh.authPublickey(user, ssh.loadKeys(privateKey, null, null));

            try (SFTPClient sftp = ssh.newSFTPClient()) {
				sftp.put("d:/temp/a.txt", "$HOME/a.txt");
			}
        }
```

an sftpexception "no such file" returned:
```
net.schmizz.sshj.sftp.SFTPException: No such file
	at net.schmizz.sshj.sftp.Response.error(Response.java:113)
	at net.schmizz.sshj.sftp.Response.ensurePacketTypeIs(Response.java:91)
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:135)
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:143)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.uploadFile(SFTPFileTransfer.java:206)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.upload(SFTPFileTransfer.java:184)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.access$100(SFTPFileTransfer.java:174)
	at net.schmizz.sshj.sftp.SFTPFileTransfer.upload(SFTPFileTransfer.java:70)
	at net.schmizz.sshj.sftp.SFTPFileTransfer.upload(SFTPFileTransfer.java:58)
	at net.schmizz.sshj.sftp.SFTPClient.put(SFTPClient.java:238)
	at com.hp.es.cto.sp.ssh.SshjTest.testUpload(SshjTest.java:29)
```

could you take a look at it? thanks

**Comment by hierynomus** [comment]
I don't think this is a bug in the library. It would be impossible to correctly determine the remote path expansion. SFTP is not associated to a shell on the remote system, and thus cannot even do shell expansions (which is what $HOME is).

**Comment by missedone** [comment]
Fine, my workaround to expand the path before sftp operation, by 'echo' the file path with the 'exec' channel
