### ISSUE TITLE
Window consumed to below 0

### ISSUE THREAD

**Issue by dronadroid** [hierynomus/sshj#203]
Getting this error for large files > 30GB

2015-06-21 15:13:37,574 ERROR [reader] net.schmizz.sshj.transport.TransportImpl: Dying because - {}
net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
        at net.schmizz.sshj.connection.channel.Window.consume(Window.java:62)
        at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:154)
        at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:368)
        at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:184)
        at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:128)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:475)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:127)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:195)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:72)

**Comment by hierynomus** [comment]
Which SSH server? Can you provide some logging and/or a reproducible testcase?

**Comment by dronadroid** [comment]
SSH Server:

debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000000

Logging:

Looks like the window size is reaching zero before it receives SSH_MSG_CHANNEL_WINDOW_ADJUST ?
or is it missing some SSH_MSG_CHANNEL_WINDOW_ADJUST  message ?

2015-07-03 19:49:29,632 INFO [main] net.schmizz.sshj.connection.ConnectionImpl: Attaching `session` channel (#0)
2015-07-03 19:49:29,636 INFO [reader] net.schmizz.sshj.connection.channel.direct.SessionChannel: Initialized - < session channel: id=0, recipient=0, localWin=[winSize=2097152], remoteWin=[winSize=0] >
2015-07-03 19:49:29,636 INFO [reader] net.schmizz.concurrent.Promise: Setting <<chan#0 / open>> to `SOME`
2015-07-03 19:49:29,636 INFO [main] net.schmizz.sshj.connection.channel.direct.SessionChannel: Will request to exec `scp -f -q -p -r ''`
2015-07-03 19:49:29,636 INFO [main] net.schmizz.sshj.connection.channel.direct.SessionChannel: Sending channel request for `exec`
2015-07-03 19:49:29,638 INFO [reader] net.schmizz.sshj.connection.channel.direct.SessionChannel: Received window adjustment for 2097152 bytes
2015-07-03 19:49:29,638 INFO [reader] net.schmizz.sshj.connection.channel.Window$Remote: Increasing by 2097152 up to 2097152
2015-07-03 19:49:29,639 INFO [reader] net.schmizz.concurrent.Promise: Setting <<chan#0 / chanreq for exec>> to `SOME`
2015-07-03 19:49:29,639 INFO [main] net.schmizz.sshj.xfer.scp.SCPEngine: Signalling: Start status OK
2015-07-03 19:49:29,639 INFO [main] net.schmizz.sshj.connection.channel.Window$Remote: Consuming by 1 down to 2097151
2015-07-03 19:49:29,672 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 27 down to 2097125
2015-07-03 19:49:29,700 INFO [main] net.schmizz.sshj.xfer.scp.SCPEngine: Read message: `T1435931237 0 1435931234 0`
2015-07-03 19:49:29,700 INFO [main] net.schmizz.sshj.xfer.scp.SCPEngine: Signalling: ACK: T
2015-07-03 19:49:29,701 INFO [main] net.schmizz.sshj.connection.channel.Window$Remote: Consuming by 1 down to 2097150
2015-07-03 19:49:29,701 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 44 down to 2097081
2015-07-03 19:49:29,702 INFO [main] net.schmizz.sshj.xfer.scp.SCPEngine: Read message: ``
2015-07-03 19:49:29,707 INFO [main] net.schmizz.sshj.xfer.scp.SCPEngine: Signalling: Remote can start transfer
2015-07-03 19:49:29,707 INFO [main] net.schmizz.sshj.connection.channel.Window$Remote: Consuming by 1 down to 2097149


2015-07-03 19:49:43,907 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 540672
2015-07-03 19:49:43,908 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 524288
2015-07-03 19:49:43,908 INFO [main] net.schmizz.sshj.connection.channel.ChannelInputStream: Sending SSH_MSG_CHANNEL_WINDOW_ADJUST to #0 for 1572864 bytes
2015-07-03 19:49:43,909 INFO [main] net.schmizz.sshj.connection.channel.Window$Local: Increasing by 1572864 up to 2097152
2015-07-03 19:49:43,909 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 2080768
..
..
2015-07-03 19:49:44,023 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 540672
2015-07-03 19:49:44,024 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 524288
2015-07-03 19:49:44,025 INFO [main] net.schmizz.sshj.connection.channel.ChannelInputStream: Sending SSH_MSG_CHANNEL_WINDOW_ADJUST to #0 for 1572864 bytes
2015-07-03 19:49:44,025 INFO [main] net.schmizz.sshj.connection.channel.Window$Local: Increasing by 1572864 up to 2097152
..
..
2015-07-03 19:49:44,169 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 49152
2015-07-03 19:49:44,170 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 32768
2015-07-03 19:49:44,179 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 16384
2015-07-03 19:49:44,180 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to 0
2015-07-03 19:49:44,261 INFO [main] net.schmizz.sshj.connection.channel.ChannelInputStream: Sending SSH_MSG_CHANNEL_WINDOW_ADJUST to #0 for 2097152 bytes
2015-07-03 19:49:44,264 INFO [reader] net.schmizz.sshj.connection.channel.Window$Local: Consuming by 16384 down to -16384
2015-07-03 19:49:44,266 ERROR [reader] net.schmizz.sshj.transport.TransportImpl: Dying because - {}
net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
        at net.schmizz.sshj.connection.channel.Window.consume(Window.java:62)
        at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:154)
        at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:368)
        at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:184)
        at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:128)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:475)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:127)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:195)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:72)
2015-07-03 19:49:44,269 INFO [reader] net.schmizz.sshj.transport.TransportImpl: Disconnected - UNKNOWN
2015-07-03 19:49:44,269 INFO [main] net.schmizz.sshj.connection.channel.Window$Local: Increasing by 2097152 up to 2080768
2015-07-03 19:49:44,274 INFO [reader] net.schmizz.sshj.transport.KeyExchanger: Got notified of net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
2015-07-03 19:49:44,280 INFO [reader] net.schmizz.sshj.connection.ConnectionImpl: Notified of net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
2015-07-03 19:49:44,282 INFO [reader] net.schmizz.sshj.connection.channel.direct.SessionChannel: Channel #0 got notified of net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
2015-07-03 19:49:44,282 INFO [reader] net.schmizz.sshj.connection.ConnectionImpl: Forgetting `session` channel (#0)
2015-07-03 19:49:44,283 INFO [reader] net.schmizz.concurrent.Promise: Setting <<chan#0 / close>> to `SOME`
2015-07-03 19:49:44,283 INFO [reader] net.schmizz.sshj.transport.TransportImpl: Setting active service to null-service
2015-07-03 19:49:44,283 INFO [reader] net.schmizz.concurrent.Promise: Setting <<transport close>> to `SOME`
2015-07-03 19:49:44,283 INFO [reader] net.schmizz.sshj.transport.Reader: Stopping

It is very difficult to reproduce this error. It happens only in a certain setup. Let me know if you need some additional debug/logs ?

**Comment by hierynomus** [comment]
I've found a potential race condition, could you recheck whether you can still reproduce this?

**Comment by hierynomus** [comment]
@dronadroid Could you check whether you can still reproduce this using a current snapshot build?

**Comment by hierynomus** [comment]
@dronadroid ping?

**Comment by hierynomus** [comment]
Assuming this is fixed with 0.16.0.
