### ISSUE TITLE
failed to compile examples

### ISSUE THREAD

**Issue by replyxf** [hierynomus/sshj#206]
sshj-master/examples$ mvn -e eclipse:eclipse
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='net.schmizz:sshj'}' and 'Vertex{label='net.schmizz:sshj'}' introduces to cycle in the graph net.schmizz:sshj --> net.schmizz:sshj
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.BuildFailureException: The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='net.schmizz:sshj'}' and 'Vertex{label='net.schmizz:sshj'}' introduces to cycle in the graph net.schmizz:sshj --> net.schmizz:sshj
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:295)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: hidden.org.codehaus.plexus.util.dag.CycleDetectedException: Edge between 'Vertex{label='net.schmizz:sshj'}' and 'Vertex{label='net.schmizz:sshj'}' introduces to cycle in the graph net.schmizz:sshj --> net.schmizz:sshj
	at hidden.org.codehaus.plexus.util.dag.DAG.addEdge(DAG.java:143)
	at hidden.org.codehaus.plexus.util.dag.DAG.addEdge(DAG.java:123)
	at org.apache.maven.project.ProjectSorter.<init>(ProjectSorter.java:118)
	at org.apache.maven.execution.ReactorManager.<init>(ReactorManager.java:99)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:288)
	... 11 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Fri Jul 17 17:46:56 EDT 2015
[INFO] Final Memory: 4M/80M

**Comment by hierynomus** [comment]
Should be fixed now, try again :)
