### ISSUE TITLE
sshj with spring concurrency

### ISSUE THREAD

**Issue by magg** [hierynomus/sshj#227]
i'm wring a backend service that monitors a few systems with @Scheduled and @Async  annotations

Out of three, only one succeeds, and other two have this bug. 

2015-11-24 06:31:36.245 ERROR 75183 --- [         reader] n.schmizz.sshj.transport.TransportImpl   : Dying because - {}

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:50)

2015-11-24 06:31:36.247 ERROR 75183 --- [cTaskExecutor-5] net.schmizz.concurrent.Promise           : <<chan#5 / close>> woke to: net.schmizz.sshj.connection.ConnectionException: Connection reset
2015-11-24 06:33:05.300 ERROR 75183 --- [         reader] n.schmizz.sshj.transport.TransportImpl   : Dying because - {}

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:50)

2015-11-24 06:33:05.302 ERROR 75183 --- [cTaskExecutor-6] net.schmizz.concurrent.Promise           : <<chan#3 / close>> woke to: net.schmizz.sshj.connection.ConnectionException: Connection reset

Anyone has successfully integrated spring and sshj code.?

Note: I'm using tomcat 7 as app container

**Comment by hierynomus** [comment]
What does your code look like? Are you sharing an SSHClient or Session between the different invocations of the services?

**Comment by magg** [comment]
closing

**Comment by ltamaster** [comment]
Did you fix this issue?
