### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by apoli86** [hierynomus/sshj#246]
Hi, 

I received an unexpected EOF error if I try to connect to a machine through ssh. I attached the full log. 

Here you can find the code use for connection. 
```
private SSHClient connect(SshCredentials credentials) throws IOException
{
		String host = credentials.getHost();
		
		SSHClient sshClient= new SSHClient();
		sshClient.addHostKeyVerifier(new PromiscuousVerifier());
		sshClient.connect(host);
				
		String user    = credentials.getUser();
		File   keyFile = credentials.getKeyFile();
		
		sshClient.authPublickey(user, keyFile.getAbsolutePath());
		
		return sshClient;
}
```
Here you can find the stacktrace: 
```
net.schmizz.sshj.connection.ConnectionException: Stream closed
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.checkClose(ChannelOutputStream.java:165)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:146)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:140)
	at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:270)
	at net.schmizz.sshj.sftp.SFTPEngine.init(SFTPEngine.java:76)
	at net.schmizz.sshj.SSHClient.newSFTPClient(SSHClient.java:635)
```

Thanks for your effort.

[log.txt](https://github.com/hierynomus/sshj/files/257403/log.txt)

**Comment by hierynomus** [comment]
The stack is from the sftp engine. The connection itself is established
fine judging from the log. What does the rest of the code look like?
Op 10 mei 2016 4:30 p.m. schreef "apoli86" <notifications@github.com>:

**Comment by apoli86** [comment]
This is the method I call. The exception is thrown when it tries to create SFTPClient instance. 

```
	public List<RemoteFile> getFilesInDirectory(final SshCredentials credentials, final RemoteFile remoteDirectory, final String filePattern) throws Exception
	{
		Preconditions.checkNotNull(credentials, "credentials");
		Preconditions.checkNotNull(remoteDirectory, "remoteDirectory");
		Preconditions.checkNotNull(filePattern, "filePattern");
		
		String remotePath = remoteDirectory.getFilePath();
		
		try(SSHClient sshClient = connect(credentials))
		{
			try (SFTPClient sftpClient = sshClient.newSFTPClient()) 
			{			
				RemoteResourceFilter filter = new RemoteResourceFilter() {
					Pattern pattern = Pattern.compile(filePattern.replace(".", "\\.").replace("*", ".*"));
					
					@Override
					public boolean accept(RemoteResourceInfo resource) {
						String filename = resource.getName();
						Matcher matcher = pattern.matcher(filename);
						
						return matcher.matches();
					}
				};
				
				List<RemoteResourceInfo> remoteResourceInfos = sftpClient.ls(remotePath, filter);
				
				return buildRemoteFileList(remoteResourceInfos);
			}
		}
	}
```

**Comment by apoli86** [comment]
Hi, 

any news about the issue? 

Thanks for your effort.

**Comment by hierynomus** [comment]
Hi,

I've looked at the log file, and you see the CLOSE coming in from the
remote system, while you're requesting the SFTP subsystem.
I think you need to have the server side logging to see why it is closing
the connection on you.



2016-05-20 12:51 GMT+02:00 apoli86 <notifications@github.com>:

**Comment by apoli86** [comment]
Hi,

the issue seems to be solved: it was a server side problem. 

Thanks
