### ISSUE TITLE
Curve25519

### ISSUE THREAD

**Issue by wlarsong** [hierynomus/sshj#249]
I am trying to do a simple connection between ECDH25519 and SSHJ.

Bouncy Castle 1.54 is installed as is i2p.jar

```
`package com.synel.config.util;

import net.schmizz.sshj.SSHClient;
import net.schmizz.sshj.common.IOUtils;
import net.schmizz.sshj.connection.channel.direct.Session;
import net.schmizz.sshj.connection.channel.direct.Session.Command;
import net.schmizz.sshj.transport.verification.PromiscuousVerifier;
import net.i2p.crypto.eddsa.spec.*;
import org.bouncycastle.math.ec.custom.djb.Curve25519;


import java.io.IOException;
import java.util.concurrent.TimeUnit;

/** This examples demonstrates how a remote command can be executed. */
public class Exec {

    public static void main(String... args)
            throws IOException {
        final SSHClient ssh = new SSHClient();
        ssh.addHostKeyVerifier(new PromiscuousVerifier());

        ssh.connect("192.168.1.52");
        try {
            ssh.authPassword("root","synergy");
            final Session session = ssh.startSession();
            try {
                final Command cmd = session.exec("ping -c 1 google.com");
                System.out.println(IOUtils.readFully(cmd.getInputStream()).toString());
                cmd.join(5, TimeUnit.SECONDS);
                System.out.println("\n** exit status: " + cmd.getExitStatus());
            } finally {
                session.close();
            }
        } finally {
            ssh.disconnect();
        }
    }

}`
```

SSHJ Error:

```
17:00:55.647 [reader] DEBUG n.s.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
17:00:55.647 [reader] DEBUG n.s.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=curve25519-sha256@libssh.org; sig=ssh-rsa; c2sCipher=aes256-ctr; s2cCipher=aes256-ctr; c2sMAC=hmac-sha2-256; s2cMAC=hmac-sha2-256; c2sComp=none; s2cComp=none ]
Exception in thread "reader" java.lang.NoClassDefFoundError: djb/Curve25519
	at net.schmizz.sshj.transport.kex.Curve25519DH.init(Curve25519DH.java:56)
	at net.schmizz.sshj.transport.kex.Curve25519SHA256.initDH(Curve25519SHA256.java:51)
	at net.schmizz.sshj.transport.kex.AbstractDHG.init(AbstractDHG.java:55)
	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:239)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:509)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:107)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:175)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
Caused by: java.lang.ClassNotFoundException: djb.Curve25519
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```

OpenSSH sees the connection coming through but then this error occurs
bcpkix and bcprov jars are in I am running git sshj-0.16-1-dev.

I see the org.bouncycastle.math.ec.custom.djb.Curve25519 declaration in SSHJ

java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Server VM (build 25.91-b14, mixed mode)

**Comment by hierynomus** [comment]
Are you sure you have all the required libraries on the java classpath?

**Comment by wlarsong** [comment]
Project is running from eclipse

.classpath FIle
<?xml version="1.0" encoding="UTF-8"?>
```
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="lib" path="bcpkix-jdk15on-1.54.jar"/>
	<classpathentry kind="lib" path="bcprov-jdk15on-1.54.jar"/>
	<classpathentry kind="lib" path="junit-4.11.jar"/>
	<classpathentry kind="lib" path="jzlib-1.1.3.jar"/>
	<classpathentry kind="lib" path="logback-classic-1.1.2.jar"/>
	<classpathentry kind="lib" path="logback-core-1.1.2.jar"/>
	<classpathentry kind="lib" path="mina-core-2.0.7.jar"/>
	<classpathentry kind="lib" path="mockito-all-1.9.5.jar"/>
	<classpathentry kind="lib" path="slf4j-api-1.7.7.jar"/>
	<classpathentry kind="lib" path="sshd-core-0.11.0.jar"/>
	<classpathentry kind="lib" path="sshj-0.16.1-dev.3.uncommitted+364a821.jar"/>
	<classpathentry kind="lib" path="i2p.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

Debug View ClassPath:

`/usr/lib/jvm/java-8-oracle/bin/java -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:55911 -Dfile.encoding=UTF-8 -classpath /opt/Synergy-WS/Infor_Config_Util/bin:/opt/Synergy-WS/Infor_Config_Util/bcpkix-jdk15on-1.54.jar:/opt/Synergy-WS/Infor_Config_Util/bcprov-jdk15on-1.54.jar:/opt/Synergy-WS/Infor_Config_Util/junit-4.11.jar:/opt/Synergy-WS/Infor_Config_Util/jzlib-1.1.3.jar:/opt/Synergy-WS/Infor_Config_Util/logback-classic-1.1.2.jar:/opt/Synergy-WS/Infor_Config_Util/logback-core-1.1.2.jar:/opt/Synergy-WS/Infor_Config_Util/mina-core-2.0.7.jar:/opt/Synergy-WS/Infor_Config_Util/mockito-all-1.9.5.jar:/opt/Synergy-WS/Infor_Config_Util/slf4j-api-1.7.7.jar:/opt/Synergy-WS/Infor_Config_Util/sshd-core-0.11.0.jar:/opt/Synergy-WS/Infor_Config_Util/sshj-0.16.1-dev.3.uncommitted+364a821.jar:/opt/Synergy-WS/Infor_Config_Util/i2p.jar com.synel.config.util.Exec`

**Comment by hierynomus** [comment]
Are you using a build system such as Maven or Gradle? Because those should
also have included the "net.vrallev.ecc:ecc-25519-java:1.0.1" library.

2016-05-20 15:11 GMT+02:00 wlarsong <notifications@github.com>:

**Comment by wlarsong** [comment]
That was it. For some reason it wouldn't download that library. It works now. Thanks!
