### ISSUE TITLE
Gradle failure in v0.17.2

### ISSUE THREAD

**Issue by jpstotz** [hierynomus/sshj#256]
When I execute `gradlew tasks` the process ends with an error:

```
09:49:02.381 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 3.011 secs
09:49:02.381 [INFO] [nl.javadude.gradle.plugins.license.LicensePlugin] Adding license tasks for sourceSet licenseMain
09:49:02.396 [INFO] [org.gradle.api.Task] Applying license defaults to task: :licenseMain
09:49:02.396 [INFO] [org.gradle.api.Task] Applying license defaults to task: :licenseFormatMain
09:49:02.396 [INFO] [nl.javadude.gradle.plugins.license.LicensePlugin] Adding license tasks for sourceSet licenseTest
09:49:02.396 [INFO] [org.gradle.api.Task] Applying license defaults to task: :licenseTest
09:49:02.396 [INFO] [org.gradle.api.Task] Applying license defaults to task: :licenseFormatTest
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter]
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter]
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter] Build file 'D:\sshj-0.17.2\build.gradle' line: 39
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter]
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'sshj'.
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter] > repository not found: D:\sshj-0.17.2
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter]
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'sshj'.
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:154)
09:49:02.396 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
09:49:02.428 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
09:49:02.428 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
09:49:02.428 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
09:49:02.428 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:492)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
09:49:02.443 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
09:49:02.459 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
09:49:02.459 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
09:49:02.459 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:48)
09:49:02.459 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
09:49:02.459 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
09:49:02.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
09:49:02.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
09:49:02.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
09:49:02.490 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
09:49:02.490 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.Swapper.swap(Swapper.java:38)
09:49:02.490 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
09:49:02.490 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.490 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
09:49:02.490 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.490 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
09:49:02.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
09:49:02.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
09:49:02.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
09:49:02.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: D:\sshj-0.17.2
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:581)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.eclipse.jgit.api.Git.open(Git.java:116)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.eclipse.jgit.api.Git.open(Git.java:99)
09:49:02.521 [ERROR] [org.gradle.BuildExceptionReporter]        at org.eclipse.jgit.api.Git$open.call(Unknown Source)
09:49:02.537 [ERROR] [org.gradle.BuildExceptionReporter]        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:84)
09:49:02.537 [ERROR] [org.gradle.BuildExceptionReporter]        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
09:49:02.537 [ERROR] [org.gradle.BuildExceptionReporter]        at java_util_concurrent_Callable$call.call(Unknown Source)
09:49:02.537 [ERROR] [org.gradle.BuildExceptionReporter]        at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy:230)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.ajoberstar.grgit.Grgit$open.call(Unknown Source)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at build_dm7v245ys2hwlhs91yhhggiuf$_run_closure4.doCall(D:\sshj-0.17.2\build.gradle:39)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
09:49:02.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
09:49:02.568 [ERROR] [org.gradle.BuildExceptionReporter]        at build_dm7v245ys2hwlhs91yhhggiuf.run(D:\sshj-0.17.2\build.gradle:38)
09:49:02.568 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
09:49:02.568 [ERROR] [org.gradle.BuildExceptionReporter]        ... 44 more
09:49:02.568 [ERROR] [org.gradle.BuildExceptionReporter]
09:49:02.568 [LIFECYCLE] [org.gradle.BuildResultLogger]
09:49:02.584 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
09:49:02.584 [LIFECYCLE] [org.gradle.BuildResultLogger]
```

**Comment by hierynomus** [comment]
Hi Jan,

I've switched to a new release plugin in gradle, which requires the git history. It seems like you've downloaded the source instead of cloning the repository, correct?

**Comment by jpstotz** [comment]
Yes, the code was downloaded from the releases section.
