### ISSUE TITLE
SCP Large Files -- local window exhausted

### ISSUE THREAD

**Issue by orism** [hierynomus/sshj#29]
Hi,

sometimes while Transmitting large files via SCP i recive following Error:

Caused by: net.schmizz.sshj.common.SSHException: Window consumed to below 0
    at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:56)
    at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:49)
    at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:572)
    at net.schmizz.sshj.transport.Reader.run(Reader.java:79)
Caused by: net.schmizz.sshj.common.SSHRuntimeException: Window consumed to below 0
    at net.schmizz.sshj.connection.channel.Window.consume(Window.java:59)
    at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:154)
    at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:364)
    at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:182)
    at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:125)
    at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:474)
    at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:127)
    at net.schmizz.sshj.transport.Decoder.received(Decoder.java:195)
    at net.schmizz.sshj.transport.Reader.run(Reader.java:72)

Sorry but i do not understand the reason why this error occurs. Neither do i have any idea how to solve it. 
I'm not sure if this is an bug or not. But i definitely  can't pin down a reason why this exception happens.

**Comment by dronadroid** [comment]
Is this resolved ?
I am still getting this error for large files
2015-06-21 15:13:37,574 ERROR [reader] net.schmizz.sshj.transport.TransportImpl: Dying because - {}
net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
        at net.schmizz.sshj.connection.channel.Window.consume(Window.java:62)
        at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:154)
        at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:368)
        at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:184)
        at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:128)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:475)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:127)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:195)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:72)

**Comment by hierynomus** [comment]
Which SSH server? Do you have a reproducible testcase?
