### ISSUE TITLE
not connect to sftp server

### ISSUE THREAD

**Issue by winneryong** [hierynomus/sshj#318]
###Use xftp software can connect,  but sshj not connect, error log :

```
[INFO ] 2017-04-10 17:49:18,713 method:net.schmizz.sshj.transport.random.BouncyCastleRandom.<init>(BouncyCastleRandom.java:48)
Generating random seed from SecureRandom.
[WARN ] 2017-04-10 17:49:20,260 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,262 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,268 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,271 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,285 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,299 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,300 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,300 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,310 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,317 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,318 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,320 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,320 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,321 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size
[WARN ] 2017-04-10 17:49:20,324 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:200)
Illegal key size or default parameters
[WARN ] 2017-04-10 17:49:20,335 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:205)
Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
[INFO ] 2017-04-10 17:49:20,517 method:net.schmizz.sshj.transport.TransportImpl.sendClientIdent(TransportImpl.java:211)
Client identity string: SSH-2.0-SSHJ_0.20.0
[INFO ] 2017-04-10 17:49:20,543 method:net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:178)
Server identity string: SSH-2.0-OpenSSH_6.6.1
[ERROR] 2017-04-10 17:49:20,632 method:net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:590)
Dying because - {}
net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `f0:0b:2a:57:45:b5:ab:bc:cc:e1:af:1f:f1:4a:83:b0` for `10.10.10.121` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:201)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
[INFO ] 2017-04-10 17:49:20,745 method:net.schmizz.sshj.transport.TransportImpl.notifyDisconnect(TransportImpl.java:192)
Disconnected - HOST_KEY_NOT_VERIFIABLE
[ERROR] 2017-04-10 17:49:20,749 method:net.schmizz.concurrent.Promise.tryRetrieve(Promise.java:175)
<<kex done>> woke to: net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `f0:0b:2a:57:45:b5:ab:bc:cc:e1:af:1f:f1:4a:83:b0` for `10.10.10.121` on port 22
Exception in thread "main" net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `f0:0b:2a:57:45:b5:ab:bc:cc:e1:af:1f:f1:4a:83:b0` for `10.10.10.121` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:201)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
```

**Comment by hierynomus** [comment]
You have not enabled high-strength ciphers. You need to download the java cryptography extensions unlimited strength files for your JDK/JRE.

See this line:
```
[WARN ] 2017-04-10 17:49:20,335 method:net.schmizz.sshj.DefaultConfig.initCipherFactories(DefaultConfig.java:205)
Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
```

**Comment by winneryong** [comment]
oh.. thanks a lot, I to be try it again.

**Comment by winneryong** [comment]
I download and replace  java cryptography extensions unlimited strength files *.jar file to  JDK_HOME/lib/security and jre/lib/security, but not work too.

error log:

[INFO ] 2017-04-10 18:13:11,532 method:net.schmizz.sshj.transport.random.BouncyCastleRandom.<init>(BouncyCastleRandom.java:48)
Generating random seed from SecureRandom.
[INFO ] 2017-04-10 18:13:11,759 method:net.schmizz.sshj.transport.TransportImpl.sendClientIdent(TransportImpl.java:211)
Client identity string: SSH-2.0-SSHJ_0.20.0
[INFO ] 2017-04-10 18:13:11,803 method:net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:178)
Server identity string: SSH-2.0-OpenSSH_6.6.1
[ERROR] 2017-04-10 18:13:11,893 method:net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:590)
Dying because - {}
net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `f0:0b:2a:57:45:b5:ab:bc:cc:e1:af:1f:f1:4a:83:b0` for `10.10.10.121` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:201)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
[INFO ] 2017-04-10 18:13:11,896 method:net.schmizz.sshj.transport.TransportImpl.notifyDisconnect(TransportImpl.java:192)
Disconnected - HOST_KEY_NOT_VERIFIABLE
[ERROR] 2017-04-10 18:13:11,897 method:net.schmizz.concurrent.Promise.tryRetrieve(Promise.java:175)
<<kex done>> woke to: net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `f0:0b:2a:57:45:b5:ab:bc:cc:e1:af:1f:f1:4a:83:b0` for `10.10.10.121` on port 22
Exception in thread "main" net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `f0:0b:2a:57:45:b5:ab:bc:cc:e1:af:1f:f1:4a:83:b0` for `10.10.10.121` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:201)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

**Comment by winneryong** [comment]
i try to use jcraft to connect sftp server,  connect success.

**Comment by winneryong** [comment]
sftp server run on Centos 7

**Comment by hierynomus** [comment]
@winneryong It seems that you have not loaded the right hot key verification.

In order to accept all host keys (ie. not verify anything), use `sshClient.addHostKeyVerifier(new PromiscuousVerifier());`
If you want to use the `known_hosts` file, use sshClient.loadKnownHosts(new File("/home/x/.ssh/known_hosts"));`

**Comment by winneryong** [comment]
@hierynomus  Is't work!  Thank you very much!  :+1:
