### ISSUE TITLE
Connection reset with SocketException when connecting to OpenSSH-Win64 

### ISSUE THREAD

**Issue by PiotrNestor** [hierynomus/sshj#323]
Environment:
sshj on Windows 10 64b connecting to OpenSSH-Win64 (v0.0.12.0)  sshd on Windows 2012

I'm getting sometimes the following error when connecting using AuthPublickey.
**The problem does happen from time to time.** 
Most often the connection works fine and using ssh/sftp is OK - so the overall configuration is good.

**Any ideas how to avoid/fix the problem?**

```
net.schmizz.sshj.transport.TransportImpl:593 - Dying because - {}
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:49)
2017-04-26 21:40:34 ERROR net.schmizz.concurrent.Promise:175 - <<chan#0 / chanreq for subsystem>> woke to: net.schmizz.sshj.connection.ConnectionException: Connection reset
```

Stack trace:
```
net.schmizz.sshj.connection.ConnectionException: Connection reset
	at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)
	at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)
	at net.schmizz.concurrent.Promise.deliverError(Promise.java:96)
	at net.schmizz.concurrent.Event.deliverError(Event.java:74)
	at net.schmizz.concurrent.ErrorDeliveryUtil.alertEvents(ErrorDeliveryUtil.java:39)
	at net.schmizz.sshj.connection.channel.AbstractChannel.notifyError(AbstractChannel.java:239)
	at net.schmizz.sshj.connection.channel.direct.SessionChannel.notifyError(SessionChannel.java:229)
	at net.schmizz.sshj.common.ErrorNotifiable$Util.alertAll(ErrorNotifiable.java:35)
	at net.schmizz.sshj.connection.ConnectionImpl.notifyError(ConnectionImpl.java:258)
	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:601)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:67)
Caused by: net.schmizz.sshj.common.SSHException: Connection reset
	at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:36)
	at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:29)
	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:595)
	... 1 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:49)
```

**Comment by vuminhkh** [comment]
Hi, 
I'm having the same error with the version 0.21.1. On a shell session, if the command takes long time to finish and the command produces no output, then the connection seems to "expire" and reset:

`[ERROR][2017-06-26 18:30:36.399]<<chan#8 / close>> woke to: net.schmizz.sshj.connection.ConnectionException: Connection reset
[ERROR][2017-06-26 18:30:36.385]Dying because - {}
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:49)`

Thanks,

Khang

**Comment by hierynomus** [comment]
Have you tried enabling keep alive? I think the socket times out.

Regards, Jeroen

Op 26 jun. 2017 6:39 p.m. schreef "vuminhkh" <notifications@github.com>:

**Comment by vuminhkh** [comment]
Thanks, It works by following your keep alive example. Just for my understanding what's the difference between the default heart beater and the keep alive ?

If keep alive works better why it is not the default setting ?

Thanks,

Khang

**Comment by hierynomus** [comment]
Main reason is that keep-alive was added later and is as far as I remember
specific to OpenSSH.

2017-06-27 0:05 GMT+02:00 vuminhkh <notifications@github.com>:
