### ISSUE TITLE
Timeout expired on SFTPClient#close()

### ISSUE THREAD

**Issue by ben-manes** [hierynomus/sshj#326]
When uploading a file, the `sftp.put()` command is appears to be successful, as I see it on the remote server. When `sftp.close()` is called, the exception is thrown and the remote file disappears. The code was based on your example, so I'm not sure what is wrong.

```java
private void uploadFile(Path file) throws IOException {
  try (Closer closer = Closer.create()) {
    SSHClient ssh = closer.register(new SSHClient());
    ssh.addHostKeyVerifier(new PromiscuousVerifier());
    ssh.connect(HOST);
    ssh.authPassword(USERNAME, PASSWORD);

    SFTPClient sftp = closer.register(ssh.newSFTPClient());
    sftp.put(new FileSystemFile(file.toFile()), file.toFile().getName());

    sftp.close();
    ssh.disconnect();
  }
}
```
```
net.schmizz.sshj.connection.ConnectionException: Timeout expired
  at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)
  at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)
 	at net.schmizz.concurrent.Promise.retrieve(Promise.java:140)
 	at net.schmizz.concurrent.Event.await(Event.java:105)
 	at net.schmizz.sshj.connection.channel.AbstractChannel.close(AbstractChannel.java:265)
 	at net.schmizz.sshj.sftp.SFTPEngine.close(SFTPEngine.java:253)
 	at net.schmizz.sshj.sftp.SFTPClient.close(SFTPClient.java:250)
```

**Comment by ben-manes** [comment]
It appears that if `sftp.close()` is not called, then it operates correctly. Perhaps the sftp server is not ACK'ing the command?

```
DEBUG net.schmizz.sshj.sftp.PacketReader: Received STATUS packet
DEBUG net.schmizz.sshj.connection.channel.direct.SessionChannel: Sending close
TRACE net.schmizz.sshj.transport.Encoder: Encoding packet #444: 61 00 00 00 00
INFO net.schmizz.sshj.transport.TransportImpl: Disconnected - BY_APPLICATION
```

**Comment by hierynomus** [comment]
I'll have a look into it. Can't promise when, current week is full of 'real
work' issues ;)

2017-04-29 0:27 GMT+02:00 Ben Manes <notifications@github.com>:

**Comment by ben-manes** [comment]
The server had a batch job moving files from the ftp. I think the close timeout is due to a server implementation bug.

**Comment by pantsaurabh29** [comment]
@ben-manes @markairwallex how did you guys get around this? I have the same issue while uploading to a server with a batch job moving files.

**Comment by ben-manes** [comment]
I set multiple timeouts which forces a disconnect at the socket layer.

```java
  /** Performs the given task on the sftp server. */
  public void execute(SftpSettings settings, CheckedConsumer<SFTPClient> task) {
    // Throttle uploads due to some hosts not handling concurrent uploads very well
    Lock lock = locks.get(settings.host());
    lock.lock();

    try (Closer closer = Closer.create()) {
      SSHClient ssh = closer.register(new SSHClient());
      ssh.addHostKeyVerifier(new PromiscuousVerifier());
      ssh.setConnectTimeout(TIMEOUT_MS);
      ssh.setTimeout(TIMEOUT_MS);
      ssh.connect(settings.host(), settings.port());
      ssh.auth(settings.username(), getAuthMethods(settings, ssh));

      SFTPClient sftp = closer.register(ssh.newSFTPClient());
      sftp.getFileTransfer().setPreserveAttributes(false);
      sftp.getSFTPEngine().setTimeoutMs(TIMEOUT_MS);

      try {
        Unchecked.consumer(task).accept(sftp);
      } finally {
        // Disconnect prior to sftp.close() to avoid a timeout due to the server not ACK'ing
        ssh.disconnect();
      }
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    } finally {
      lock.unlock();
    }
  }
```

**Comment by pantsaurabh29** [comment]
Hence doing away with the sftp.close() altogether. I have a similar implementation without the timeout in the SFTP client though. Thanks @ben-manes will try this.
