### ISSUE TITLE
Window consumed to below 0 on version com.hierynomus:sshj:0.16.0

### ISSUE THREAD

**Issue by gfrnndz** [hierynomus/sshj#328]
Here is the stack trace that is being reported when failure occurs.

[2017-05-05T09:03:31.092+0000] [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - {}
net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
	at net.schmizz.sshj.connection.channel.Window.consume(Window.java:62)
	at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:137)
	at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:347)
	at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:161)
	at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:135)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:506)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:107)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:175)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)

**Comment by hierynomus** [comment]
Which version is this against, and do you have some more logging of when
this happens?

Thanks!

2017-05-08 20:37 GMT+02:00 gfrnndz <notifications@github.com>:

**Comment by gfrnndz** [comment]
We are using version 0.16.0.  This is the net.schmizz debug that is captured.  The error occurs when we are running a script to retrieve device information through a ssh session and the session disconnects.

**Comment by hierynomus** [comment]
Are you able to reproduce this using the latest version of SSHJ also (0.21.1)?

**Comment by gfrnndz** [comment]
I haven't tried that version yet.  I will try to reproduce on that version.

**Comment by gfrnndz** [comment]
It still appears to occur in 0.21.1

Here are the debug messages

[2017-05-09T17:47:43.685+0000] [scriptexec-akka.actor.default-dispatcher-71] INFO  net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-dropbear_0.53.1
[2017-05-09T17:47:49.084+0000] [scriptexec-akka.actor.default-dispatcher-68] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'term length 0'
[2017-05-09T17:47:49.515+0000] [scriptexec-akka.actor.default-dispatcher-67] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'term len 0'
[2017-05-09T17:47:49.945+0000] [scriptexec-akka.actor.default-dispatcher-72] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'show table interfaces efm-group'
[2017-05-09T17:47:51.290+0000] [scriptexec-akka.actor.default-dispatcher-72] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'term length 0'
[2017-05-09T17:47:52.319+0000] [scriptexec-akka.actor.default-dispatcher-72] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'term len 0'
[2017-05-09T17:47:52.585+0000] [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - {}
net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
	at net.schmizz.sshj.connection.channel.Window.consume(Window.java:63)
	at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:133)
	at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:369)
	at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:171)
	at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:130)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
[2017-05-09T17:47:52.594+0000] [reader] INFO  net.schmizz.sshj.transport.TransportImpl - Disconnected - UNKNOWN
[2017-05-09T17:47:52.600+0000] [stdout] ERROR net.schmizz.sshj.common.StreamCopier - In pipe from < ChannelInputStream for Channel #0 > to show table interfaces efm-group

**Comment by hierynomus** [comment]
Thanks for testing. Some questions to make it easier to troubleshoot/fix:

- Which SSH server is it connecting against?
- Do you have some code to reproduce?
- Can you also supply the TRACE level logging?

**Comment by gfrnndz** [comment]
The SSH server is a device in which are trying to access and gather PM statistics when the fail occurs.
The sshj is being used as part of our management software to configure and monitoring different devices.  I don't have code to share to help reproduce this problem but I'm able to reproduce on my setup.

As for TRACE level logging.  I don't think so.  Is there something I can enable to get the info you need to help debug?

**Comment by hierynomus** [comment]
trace level logging can be acquired by changing the `logback.xml` file to
log trace level messages for sshj.

As I've not seen this in regular tests, can you disclose any info about
what the device runs, or what kind of device it is (commercial or custom)

2017-05-10 15:47 GMT+02:00 gfrnndz <notifications@github.com>:

**Comment by gfrnndz** [comment]
We are accessing commercial telecom equipment to gather interface stats on all interfaces on the shelf.
I see the logback.xml and is currently set to INFO level.  I will change to TRACE and retest.

**Comment by hierynomus** [comment]
Thanks!

2017-05-10 16:30 GMT+02:00 gfrnndz <notifications@github.com>:

**Comment by gfrnndz** [comment]
I'm not seeing any new debug.   Maybe I'm looking at the wrong place but the exception from sshj is return the same info.

[2017-05-10T14:43:27.432+0000] [scriptexec-akka.actor.default-dispatcher-17] INFO  net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.21.1
[2017-05-10T14:43:27.436+0000] [scriptexec-akka.actor.default-dispatcher-49] INFO  com.adtran.apps.scriptexec.Frontend - INDEXER: com.adtran.apps.scriptexec.kafkaconnect.NullIndexer$@4ec8eec8
[2017-05-10T14:43:27.437+0000] [scriptexec-akka.actor.default-dispatcher-49] INFO  com.adtran.apps.scriptexec.Frontend - showtableintefmgroup executeScripts result: Success(())
[2017-05-10T14:43:27.772+0000] [scriptexec-akka.actor.default-dispatcher-17] INFO  net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-dropbear_0.53.1
[2017-05-10T14:43:32.747+0000] [scriptexec-akka.actor.default-dispatcher-50] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'term length 0'
[2017-05-10T14:43:33.183+0000] [scriptexec-akka.actor.default-dispatcher-54] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'show table interfaces efm-group'
[2017-05-10T14:43:34.768+0000] [scriptexec-akka.actor.default-dispatcher-50] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'term length 0'
[2017-05-10T14:43:34.794+0000] [scriptexec-akka.actor.default-dispatcher-52] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'term length 0'
[2017-05-10T14:43:36.018+0000] [scriptexec-akka.actor.default-dispatcher-53] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'show table interfaces efm-group'
[2017-05-10T14:43:36.027+0000] [scriptexec-akka.actor.default-dispatcher-17] INFO  com.adtran.apps.scriptexec.ssh.SshClient - Sending command 'show table interfaces efm-group'
[2017-05-10T14:43:41.315+0000] [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - {}
net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
	at net.schmizz.sshj.connection.channel.Window.consume(Window.java:63)
	at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:133)
	at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:369)
	at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:171)
	at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:130)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
[2017-05-10T14:43:41.335+0000] [reader] INFO  net.schmizz.sshj.transport.TransportImpl - Disconnected - UNKNOWN
[2017-05-10T14:43:41.354+0000] [stdout] ERROR net.schmizz.sshj.common.StreamCopier - In pipe from < ChannelInputStream for Channel #0 > to show table interfaces efm-group

**Comment by gfrnndz** [comment]
So I think I got TRACE messages to show up.


[2017-05-10T15:36:01.106+0000] [reader] TRACE net.schmizz.sshj.transport.Decoder - Received packet #14: 5e 00 00 00 00 00 00 16 85 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 53 74 61 74 75 73 20 20 20
[2017-05-10T15:36:01.108+0000] [reader] TRACE net.schmizz.sshj.transport.TransportImpl - Received packet CHANNEL_DATA
[2017-05-10T15:36:01.112+0000] [reader] DEBUG net.schmizz.sshj.connection.channel.Window$Local - Consuming by 5765 down to -1920
[2017-05-10T15:36:01.112+0000] [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - {}
net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
	at net.schmizz.sshj.connection.channel.Window.consume(Window.java:63)
	at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:133)
	at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:369)
	at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:171)
	at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:130)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
[2017-05-10T15:36:01.117+0000] [reader] INFO  net.schmizz.sshj.transport.TransportImpl - Disconnected - UNKNOWN
[2017-05-10T15:36:01.118+0000] [stdout] DEBUG net.schmizz.sshj.connection.channel.ChannelInputStream - Sending SSH_MSG_CHANNEL_WINDOW_ADJUST to #0 for 6016 bytes
[2017-05-10T15:36:01.118+0000] [stdout] TRACE net.schmizz.sshj.transport.Encoder - Encoding packet #8: 5d 00 00 00 00 00 00 17 80
[2017-05-10T15:36:01.120+0000] [stdout] DEBUG net.schmizz.sshj.connection.channel.Window$Local - Increasing by 6016 up to 4096
[2017-05-10T15:36:01.118+0000] [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Got notified of net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
[2017-05-10T15:36:01.120+0000] [reader] DEBUG net.schmizz.sshj.connection.ConnectionImpl - Notified of net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
[2017-05-10T15:36:01.122+0000] [reader] DEBUG net.schmizz.sshj.connection.channel.direct.SessionChannel - Channel #0 got notified of net.schmizz.sshj.connection.ConnectionException: Window consumed to below 0
[2017-05-10T15:36:01.124+0000] [reader] DEBUG net.schmizz.sshj.connection.ConnectionImpl - Forgetting `session` channel (#0)
[2017-05-10T15:36:01.124+0000] [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<chan#0 / close>> to `SOME`
[2017-05-10T15:36:01.127+0000] [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Setting active service to null-service
[2017-05-10T15:36:01.136+0000] [stdout] ERROR net.schmizz.sshj.common.StreamCopier - In pipe from < ChannelInputStream for Channel #0 > to show table interfaces efm-group.

**Comment by hierynomus** [comment]
Great, could you post possibly the entire log from connect (identification
exchange) to the failure? That allows me to better pinpoint why the error
occurs.

If you're not comfortable putting this on Github, feel free to send it to
my mail.

Regards,
Jeroen

2017-05-10 17:42 GMT+02:00 gfrnndz <notifications@github.com>:

**Comment by gfrnndz** [comment]
I no longer have the log file.  I will have to reproduce the failure.  I will send you the log messages from the connect to the failure.

**Comment by gfrnndz** [comment]
Here is the entire log I captured when I retested and caused the failure.


[script-exec.txt](https://github.com/hierynomus/sshj/files/993320/script-exec.txt)

**Comment by gfrnndz** [comment]
Just checking if you the log I provided is enough to debug issue?

**Comment by hierynomus** [comment]
Haven't looked yet, sorry. Will get around to it this week i think.

Op 15 mei 2017 11:49 a.m. schreef "gfrnndz" <notifications@github.com>:

**Comment by gfrnndz** [comment]
Did you get a chance to start debugging this issue?
