### ISSUE TITLE
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods

### ISSUE THREAD

**Issue by McFcologne** [hierynomus/sshj#342]
Im using this component for years and everything worked fine until something, i dont know what, changed at the server i connect to (the admin from the other end changed "nothing", he said).

My log shows me the following:
```
2017-07-24 11:49:30 | INFO  | net.schmizz.sshj.transport.TransportImpl |   132 | Client identity string: SSH-2.0-SSHJ_0_9_2
2017-07-24 11:49:30 | INFO  | net.schmizz.sshj.transport.TransportImpl |   142 | Server identity string: SSH-2.0-OpenSSH_5.3
2017-07-24 11:49:33 | INFO  | net.schmizz.sshj.transport.TransportImpl |    73 | Disconnected - BY_APPLICATION
2017-07-24 11:49:33 | ERROR |  ??.???.???????.???????.???.ExportWorker |   121 | Caught exception during billing process 
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:217)
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:193)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:278)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:248)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:232)
	at ??.???.???????.???????.???.ExportWorker.run(ExportWorker.java:90)
	at ??.???.???????.???????.???.Export.main(Export.java:20)
```

The error occours at this line:
`ssh.authPassword(config.getString("export.user"), config.getString("export.pass"));
`
The user and password are definitely correct and im also still able to login using WinSCP with that data.

WinSCP is showing me the following info:
```
File transfer protocol = SFTP-3
Cryptographic protocol = SSH-2
SSH implementation = OpenSSH_5.3
Encryption algorithm = aes
Compression = No
```

so it looks like java is using the exact same ssh and open ssh as WinSCP... Any Idea?

**Comment by hierynomus** [comment]
Have ypu loaded bouncycastle? I think they might have disabled lowstrrngth
encryption on the server side. Bouncycastle should allow you to use
highstrength encryption.

Op 24 jul. 2017 12:59 p.m. schreef "Michael Fritzsche" <
notifications@github.com>:

**Comment by hierynomus** [comment]
Any update?

**Comment by hierynomus** [comment]
CLosing due to inactivity

**Comment by McFcologne** [comment]
I loaded bouncy castle, but i still get the same error...

**Comment by yoloz** [comment]
i have same error too
