### ISSUE TITLE
Gradle integration won't work

### ISSUE THREAD

**Issue by pun-ky** [hierynomus/sshj#347]
I am developing a Gradle plugin which will use sshj under the hood, example snippet (Kotlin):

```kotlin
val ssh = SSHClient(config)
   
        ssh.loadKnownHosts()
        ssh.connect(host)
        try {
            ssh.authPublickey(user)

            val sftp = ssh.newSFTPClient()
            try {
                val attrs = sftp.stat(url.path)
            } finally {
                sftp.close()
            }
        } finally {
            ssh.disconnect()
        }
```

when I run code above with `gradle --no-daemon` it is working properly, but when I run daemon, exception occurring:

```
Caused by: net.schmizz.sshj.transport.TransportException: java.security.spec.InvalidKeySpecException: key spec not recognized
        at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
        at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)
        at net.schmizz.concurrent.Promise.deliverError(Promise.java:96)
        at net.schmizz.concurrent.Event.deliverError(Event.java:74)
        at net.schmizz.concurrent.ErrorDeliveryUtil.alertEvents(ErrorDeliveryUtil.java:34)
        at net.schmizz.sshj.transport.KeyExchanger.notifyError(KeyExchanger.java:386)
        at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:600)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:67)
Caused by: net.schmizz.sshj.common.SSHException: java.security.spec.InvalidKeySpecException: key spec not recognized
        at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:36)
        at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:29)
        at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:595)
        ... 1 more
Caused by: net.schmizz.sshj.common.SSHRuntimeException: java.security.spec.InvalidKeySpecException: key spec not recognized
        at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:466)
        at net.schmizz.sshj.transport.kex.AbstractDHG.next(AbstractDHG.java:66)
        at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:358)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
Caused by: java.security.GeneralSecurityException: java.security.spec.InvalidKeySpecException: key spec not recognized
        at net.schmizz.sshj.common.KeyType$3.readPubKeyFromBuffer(KeyType.java:168)
        at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:464)
        ... 6 more
Caused by: java.security.spec.InvalidKeySpecException: key spec not recognized
        at org.bouncycastle.jcajce.provider.asymmetric.util.BaseKeyFactorySpi.engineGeneratePublic(Unknown Source)
        at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi.engineGeneratePublic(Unknown Source)
        at java.security.KeyFactory.generatePublic(KeyFactory.java:334)
        at net.schmizz.sshj.common.KeyType$3.readPubKeyFromBuffer(KeyType.java:166)
        ... 7 more


```

any ideas how to solve it?

**Comment by hierynomus** [comment]
Not without a lot more logging. If it works without the daemon but not with, it could be a classpath issue? Maybe the daemon does not load a library, or maybe an older version accidentally?

**Comment by pun-ky** [comment]
yep I am also thinking about the classpath, but I don't have any idea to fix it right now. I am looking for inspiration ;) maybe someone will suggest sth interesting :)

**Comment by pun-ky** [comment]
looks like it will be that https://stackoverflow.com/a/36262268 , but how to fix that

**Comment by hierynomus** [comment]
Have you tried to mark the bouncycastle jars as a classpath dependency in
the buildscript block?

2017-08-11 16:52 GMT+02:00 Krystian Panek <notifications@github.com>:

**Comment by pun-ky** [comment]
when project using plugin adds it as classpath dependency it is working, but it will be not elegant to require plugin users to perform this additional step :/

**Comment by pun-ky** [comment]
maybe that is root cause?

```
Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
```
?

**Comment by pun-ky** [comment]
yep, when I applied this fix, https://stackoverflow.com/a/41002560 the issue is gone. maybe this check should be more passive in case of Gradle daemon? I think that maybe there is some race condition somewhere

**Comment by hierynomus** [comment]
There is a workaround which I have in my mind, but it is non-trivial. Depending on the JCE as we do know, just requires you to load high strength encryption if you need it.

**Comment by hierynomus** [comment]
Closing this as it is fixed. And mentioning #82 which is what I was hinting at.
