### ISSUE TITLE
Using Mountain Duck - Failure with SSHJ

### ISSUE THREAD

**Issue by amatzen** [hierynomus/sshj#349]
`2017-08-15 22:42:25,693 [Thread-13] WARN  ch.iterate.mountainduck.fs.SessionFilesystem - Finalize file system callback SessionFilesystem{bookmark=Host{credentials=Credentials{user='root'}, hostname='matzen.it', defaultpath='null', port=22, protocol=Profile{parent=sftp, image=null}}, controller=ch.iterate.mountainduck.fs.FilesystemController@25b5e70}
2017-08-15 22:43:08,320 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Broken transport; encountered EOF
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
	at net.schmizz.sshj.transport.Reader.run(Reader.java:57)
2017-08-15 22:43:15,936 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Broken transport; encountered EOF
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
	at net.schmizz.sshj.transport.Reader.run(Reader.java:57)
2017-08-16 15:13:29,486 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Broken transport; encountered EOF
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
	at net.schmizz.sshj.transport.Reader.run(Reader.java:57)
2017-08-16 16:00:51,836 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Broken transport; encountered EOF
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
	at net.schmizz.sshj.transport.Reader.run(Reader.java:57)`

**Comment by hierynomus** [comment]
Have you asked @dkocher who developed CyberDuck and MountainDuck?

**Comment by amatzen** [comment]
Yes, he gave me instructions to update it, however doesn't work yet :(
