### ISSUE TITLE
When mkdirs using Multiple thread,it Failure

### ISSUE THREAD

**Issue by onyas** [hierynomus/sshj#360]
logs

net.schmizz.sshj.sftp.SFTPException: Failure
	at net.schmizz.sshj.sftp.Response.error(Response.java:136)
	at net.schmizz.sshj.sftp.Response.ensureStatusIs(Response.java:129)
	at net.schmizz.sshj.sftp.Response.ensureStatusPacketIsOK(Response.java:122)
	at net.schmizz.sshj.sftp.SFTPEngine.makeDir(SFTPEngine.java:182)
	at net.schmizz.sshj.sftp.SFTPEngine.makeDir(SFTPEngine.java:187)
	at net.schmizz.sshj.sftp.SFTPClient.mkdir(SFTPClient.java:84)
	at net.schmizz.sshj.sftp.SFTPClient.mkdirs(SFTPClient.java:102)
	at net.schmizz.sshj.examples.SFTPUploadWithPwd$UploadThread.run(SFTPUploadWithPwd.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

version 0.19.0
the version of 0.21.1 has the same error

code looks like 

       @Override
        public void run() {
            try {
                String fileName = file.substring(file.lastIndexOf("/"));
                SFTPClient sftp = new SFTPUploadWithPwd().getClient(userId, userName, pwd);
                sftp.mkdirs("/upload/var/log/" + userId);
                sftp.put(new FileSystemFile(file), "/upload/var/log/" + userId + fileName);
            } catch (Exception e) {
                System.out.print("userId " + userId + " file " + file);
                e.printStackTrace();
            }
        }

userId may be same

**Comment by hierynomus** [comment]
Correct, `mkdirs` is not a threadsafe operation, as it will cut the path up, stat the existence of each part and then in turn it will call `mkdir` for each part that does not exist.

I can optimize the loop slightly to lessen the chances of this happening. But it will still not be threadsafe then. I'm not inclined to make this method threadsafe, as that has enormous impact on the throughput of unrelated `mkdirs` calls.

**Comment by onyas** [comment]
All right,I get it
