### ISSUE TITLE
RSA key authentication causes TimeoutException.

### ISSUE THREAD

**Issue by marcvg** [hierynomus/sshj#363]
Hi,

While our code works perfectly locally, it fails to authenticate with a private key on a zlin server. It looks like the loadKeys method takes longer than 30 seconds.

2017-09-22 10:19:03,197 [WorkManager.DefaultWorkManager : 7] INFO - [n.s.s.t.TransportImpl] - Client identity string: SSH-2.0-SSHJ_0.21.1
2017-09-22 10:19:03,208 [WorkManager.DefaultWorkManager : 7] INFO - [n.s.s.t.TransportImpl] - Server identity string: SSH-2.0-OpenSSH_5.3
2017-09-22 10:19:03,334 [WorkManager.DefaultWorkManager : 7] DEBUG - [n.s.sshj.SSHClient] - Key exchange took 0.123 seconds
2017-09-22 10:19:03,334 [WorkManager.DefaultWorkManager : 7] DEBUG - [c.v.i.b.d.s.ScpSender] - Loading rsa key '/home/appusr/.ssh/id_rsa'
2017-09-22 10:19:33,425 [WorkManager.DefaultWorkManager : 7] ERROR - [c.v.i.b.d.s.ScpSender] - Exhausted available authentication methods net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230) ~[sshj-0.21.1.jar:na]
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:345) ~[sshj-0.21.1.jar:na]
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:364) ~[sshj-0.21.1.jar:na]
        at c.v.i.b.d.s.ScpSender.send(ScpSender.java:49) ~[dwe-1.1.25-SNAPSHOT.jar:na]
        at c.v.i.b.d.d.facade.FacadeImpl.transfer(FacadeImpl.java:1342) [dwe-1.1.25-SNAPSHOT.jar:na]
        at c.v.i.b.d.d.facade.FacadeImpl$6.run(FacadeImpl.java:1317) [dwe-1.1.25-SNAPSHOT.jar:na]
        at org.springframework.scheduling.commonj.DelegatingWork.run(DelegatingWork.java:61) [spring-context-support-2.5.6.SEC03.jar:2.5.6.SEC03]
        at com.ibm.ws.asynchbeans.J2EEContext$RunProxy.run(J2EEContext.java:267) [com.ibm.ws.runtime.jar:na]
        at java.security.AccessController.doPrivileged(AccessController.java:400) [na:1.7.0]
        at com.ibm.ws.asynchbeans.J2EEContext.run(J2EEContext.java:1165) [com.ibm.ws.runtime.jar:na]
        at com.ibm.ws.asynchbeans.WorkWithExecutionContextImpl.go(WorkWithExecutionContextImpl.java:199) [com.ibm.ws.runtime.jar:na]
        at com.ibm.ws.asynchbeans.CJWorkItemImpl.run(CJWorkItemImpl.java:236) [com.ibm.ws.runtime.jar:na]
        at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1881) [com.ibm.ws.runtime.jar:na]
Caused by: net.schmizz.sshj.userauth.UserAuthException: Timeout expired
        at net.schmizz.sshj.userauth.UserAuthException$1.chain(UserAuthException.java:33) ~[sshj-0.21.1.jar:na]
        at net.schmizz.sshj.userauth.UserAuthException$1.chain(UserAuthException.java:26) ~[sshj-0.21.1.jar:na]
        at net.schmizz.concurrent.Promise.retrieve(Promise.java:140) ~[sshj-0.21.1.jar:na]
        at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:73) ~[sshj-0.21.1.jar:na]
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:224) ~[sshj-0.21.1.jar:na]
        ... 12 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Timeout expired
        ... 15 common frames omitted

Using sshj-0.21.1
User/password authentication works. Any idea where to look? 

Best regards,
Marc.

**Comment by marcvg** [comment]
What we know so far: it runs fine when execute from a jar. It fails when deployed on a Websphere application server.
