### ISSUE TITLE
Can't transfer file to Windows (SSH_MSG_UNIMPLEMENTED)

### ISSUE THREAD

**Issue by pascalrobert** [hierynomus/sshj#376]
Hi,

I'm working on a Web app that will transfer files to virtual machines, including Windows 7/8/10 VMs. I have installed OpenSSH 7.5 on those machines, but when I try to copy files to it, I get:

```
n.s.sshj.SSHClient: Attempting to load key from: /etc/vmix/id_rsa
n.s.s.t.TransportImpl: Dying because - {}
net.schmizz.sshj.common.SSHException: Unexpected: SSH_MSG_UNIMPLEMENTED
	at net.schmizz.sshj.AbstractService.notifyUnimplemented(AbstractService.java:63)
	at net.schmizz.sshj.transport.TransportImpl.gotUnimplemented(TransportImpl.java:579)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:514)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
n.s.s.t.TransportImpl: Disconnected - PROTOCOL_ERROR
n.s.c.Promise: <<service accept>> woke to: net.schmizz.sshj.transport.TransportException: Unexpected: SSH_MSG_UNIMPLEMENTED
net.schmizz.sshj.transport.TransportException: Unexpected: SSH_MSG_UNIMPLEMENTED
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)
	at net.schmizz.concurrent.Promise.deliverError(Promise.java:96)
	at net.schmizz.concurrent.Event.deliverError(Event.java:74)
	at net.schmizz.concurrent.ErrorDeliveryUtil.alertEvents(ErrorDeliveryUtil.java:34)
	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:599)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:67)
Caused by: net.schmizz.sshj.common.SSHException: [PROTOCOL_ERROR] Unexpected: SSH_MSG_UNIMPLEMENTED
	at net.schmizz.sshj.AbstractService.notifyUnimplemented(AbstractService.java:63)
	at net.schmizz.sshj.transport.TransportImpl.gotUnimplemented(TransportImpl.java:579)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:514)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
```

The key file is valid and the path is good. I can use scp from my Mac to copy to the same host without any problems. 

I do call authPublickey, so I don't know what's happening. And yes, the user running the app do have access to the key file.

```
SSHClient sshClient= new SSHClient();
sshClient.addHostKeyVerifier(new PromiscuousVerifier());
sshClient.connect(clone.getAdresseIP());
sshClient.authPublickey("druide", "/etc/vmix/id_rsa");
sshClient.newSCPFileTransfer().upload(new FileSystemFile(artefact), "/Users/Druide/Desktop/");
```

**Comment by hierynomus** [comment]
Can you increase the logging level. It's not clear where it is currently failing.
Also it's important to look at the SSH server logging. It's sending an UNIMPLEMENTED packet. This means that it got something it didn't understand.
