### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by j0kkeri** [hierynomus/sshj#402]
I have a problem authenticating to SFTP server:

> WARNING: Server identification has bad line ending, was expecting a '\r\n' however got: '1' (hex: 31)
> helmi 22, 2018 8:35:39 AP. org.slf4j.impl.JCLLoggerAdapter warn
> WARNING: Will treat the identification of this server 'SSH-1.99-OpenSSH_7.3p1+sftpfilecontrol-v1.3-hpn14v11' leniently
> net.schmizz.sshj.transport.TransportException: Socket closed
> 	at net.schmizz.sshj.transport.TransportImpl.write(TransportImpl.java:454)
> 	at net.schmizz.sshj.transport.TransportImpl.sendServiceRequest(TransportImpl.java:357)
> 	at net.schmizz.sshj.transport.TransportImpl.reqService(TransportImpl.java:340)
> 	at net.schmizz.sshj.AbstractService.request(AbstractService.java:74)
> 	at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:65)
> 	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:225)
> 	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:206)
> 	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:292)
> 	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:262)
> 	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:246)
> 	at client.transfer.sshj.SSHJTransfer.initialize(Unknown Source)
> 	at client.transfer.sshj.sftp.SSHJSFTPTransfer.initialize(Unknown Source)
> 	at client.transfer.sshj.sftp.SSHJSFTPTransferSource.checkServerConnectionLogin(Unknown Source)
> 	at client.job.TransferJobCheckServerSourceConnetion.execute(Unknown Source)
> 	at client.job.AbstractJob.executeJob(Unknown Source)
> 	at client.configuration.ConfigurationRunnerCheckServerConnection.execute(Unknown Source)
> 	at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
> 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
> Caused by: java.net.SocketException: Socket closed
> 	at java.net.SocketOutputStream.socketWrite(Unknown Source)
> 	at java.net.SocketOutputStream.write(Unknown Source)
> 	at net.schmizz.sshj.transport.TransportImpl.write(TransportImpl.java:451)
> 	... 17 more

Also:

> FINE: Requesting password for [AccountResource] xxxxx@xxx.xxx.xxx.xxx
> helmi 22, 2018 8:35:39 AP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Awaiting <<authenticated>>
> helmi 22, 2018 8:35:39 AP. org.slf4j.impl.JCLLoggerAdapter error
> SEVERE: Dying because - Broken transport; encountered EOF
> net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
> 	at net.schmizz.sshj.transport.Reader.run(Reader.java:57)
> 
> helmi 22, 2018 8:35:39 AP. org.slf4j.impl.JCLLoggerAdapter info
> INFO: Disconnected - UNKNOWN
> helmi 22, 2018 8:35:39 AP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Got notified of net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
> helmi 22, 2018 8:35:39 AP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Notified of net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
> helmi 22, 2018 8:35:39 AP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Setting active service to null-service
> helmi 22, 2018 8:35:39 AP. org.slf4j.impl.JCLLoggerAdapter error
> SEVERE: <<authenticated>> woke to: net.schmizz.sshj.userauth.UserAuthException: Broken transport; encountered EOF

I found other similar issues when disconnecting server but this happens in authenticating...
I am using version 0.23.0

I tried even ignoring this error but then ending up to "Not connected" error.

**Comment by j0kkeri** [comment]
NoteForMySelf: Problem might be in 'password' type authenticating, eg. WinSCP automatically falls to 'keyboard-interactive' if 'password' fails.

**Comment by j0kkeri** [comment]
Ok, now I'm pretty sure that server has some failure in password-type authenticating and server closes the connection as the authentication fails (maybe this is why SSHJ wont work though it should "fallback basic challenge-response authentication")

With other SSH-lib (Ganymed) I am able to connect if I go straight to "keyboard-interactive"

Can anyone please provide help how is the "keyboard-interactive" type authentication done as primary method?
This I have tried:
```
            PasswordFinder pwf = new PasswordFinder() {

                @Override
                public char[] reqPassword(Resource<?> resource) {
                    return "myPW".toCharArray().clone();
                }

                @Override
                public boolean shouldRetry(Resource<?> resource) {
                    return false;
                }

            };
            ssh.auth("username", new AuthKeyboardInteractive(
                    new PasswordResponseProvider(pwf)));
```
Just getting: 

> net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods

**Comment by hierynomus** [comment]
Can you register an issue on Github? Also please provide the trace level
logging as well as server side logging. SSHJ does fallback to
keyboard-interactive if you use the SSHClient.authPassword(String username,
PasswordFinder pfinder) method.

Regards,
Jeroen

2018-02-23 11:52 GMT+01:00 j0kkeri <notifications@github.com>:

**Comment by jstevej** [comment]
I think I just ran into the same issue:

  *tificationStringParser Server identification has bad line ending, was expecting a '\r\n' however got: ']' 
  (hex: 5d) 
  *tificationStringParser Will treat the identification of this server 'SSH-2.0-X PKIX[10.1]' leniently 
  TransportImpl Server identity string: SSH-2.0-X PKIX[10.1] 
  TransportImpl Dying because - parameter object not a ECParameterSpec
  TransportImpl net.schmizz.sshj.transport.TransportException: [KEY_EXCHANGE_FAILED] parameter object not a ECParameterSpec 
  TransportImpl at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:240) 
  TransportImpl at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:356) 
  TransportImpl at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503) 
  TransportImpl at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
  TransportImpl at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170) 
  TransportImpl at net.schmizz.sshj.transport.Reader.run(Reader.java:59) 
  TransportImpl Caused by: java.security.InvalidAlgorithmParameterException: parameter object not a ECParameterSpec 
  TransportImpl at org.spongycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.initialize(KeyPairGeneratorSpi.java:142) 
  TransportImpl at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:192) 
  TransportImpl at net.schmizz.sshj.transport.kex.ECDH.init(ECDH.java:45) 
  TransportImpl at net.schmizz.sshj.transport.kex.ECDHNistP.initDH(ECDHNistP.java:82) 
  TransportImpl at net.schmizz.sshj.transport.kex.AbstractDHG.init(AbstractDHG.java:46) 
  TransportImpl at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:236) 
  TransportImpl ... 5 more 
  TransportImpl Disconnected - KEY_EXCHANGE_FAILED 
  n*.s*.c*.Promise <<kex done>> woke to: net.schmizz.sshj.transport.TransportException: [KEY_EXCHANGE_FAILED] parameter object not a ECParameterSpec

I'm running on Android with spongycastle. I'm authenticating via:
  client.authPassword(username, password);

Any thoughts?

**Comment by jstevej** [comment]
I tracked it down to java/net/schmizz/sshj/transport/kex/ECDHNistP.java, line 82. The ECNamedCurveGenParameterSpec it's creating comes from org.bouncycastle.jce.spec.ECNamedCurveGenParameterSpec, which is coming from the broken bouncycastle that ships with Android.

I just replaced org.bouncycastle in all the imports with org.spongycastle, rebuilt sshj, and now it works.

I'm not sure what that means for a long-term fix, but I can at least move forward now.
