### ISSUE TITLE
net.schmizz.sshj.transport.TransportException [hmac-sha2-512-etm@openssh.com, hmac-sha2-256-etm@openssh.com, umac-128-etm@openssh.com]

### ISSUE THREAD

**Issue by saimsiddiqui** [hierynomus/sshj#403]
Hello,

We were using JSCH library for SSH but the server updated to use newer key-exchange protocol (curve25519-sha256@libssh.org,curve25519-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512)

So we looked into SSHJ and found that it supports these protocols but not it is failing due to:

net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [hmac-sha1, hmac-sha1-96, hmac-md5, hmac-md5-96, hmac-sha2-256, hmac-sha2-512] and [hmac-sha2-512-etm@openssh.com, hmac-sha2-256-etm@openssh.com, umac-128-etm@openssh.com]
	at net.schmizz.sshj.transport.Proposal.firstMatch(Proposal.java:145) ~[sshj-0.23.0.jar:?]
	at net.schmizz.sshj.transport.Proposal.negotiate(Proposal.java:132) ~[sshj-0.23.0.jar:?]
	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:218) ~[sshj-0.23.0.jar:?]
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:350) ~[sshj-0.23.0.jar:?]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503) ~[sshj-0.23.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102) ~[sshj-0.23.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170) ~[sshj-0.23.0.jar:?]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59) ~[sshj-0.23.0.jar:?]

Seems like can't agree because *mac-*-etm is not supported by SSHJ.

We can't change the configuration of the server. Any help will be greatly appreciated.

Thanks

**Comment by hierynomus** [comment]
Can you submit a github issue to track this. I've looked into it, it should
be possible to support -etm MACs, however it is not as simple as adding a
new MAC to the lib, as regular MACs do a MAC-then-Encrypt, whereas -etm
MACs are Encrypt-then-MAC.

Regards,
Jeroen

2018-02-23 21:43 GMT+01:00 saimsiddiqui <notifications@github.com>:
