### ISSUE TITLE
Illegal Access Error for Bouncycastle methods

### ISSUE THREAD

**Issue by DImuthuUpe** [hierynomus/sshj#410]
I'm trying to run following simple two lines and got following error. I tried both 0.24.0 and 0.23.0 versions. What could be the reason for that?

final SSHClient ssh = new SSHClient();
ssh.connect(host);

Exception in thread "reader" java.lang.IllegalAccessError: tried to access method org.bouncycastle.asn1.ASN1Integer.<init>([B)V from class net.schmizz.sshj.signature.SignatureECDSA
	at net.schmizz.sshj.signature.SignatureECDSA.asnEncode(SignatureECDSA.java:129)
	at net.schmizz.sshj.signature.SignatureECDSA.verify(SignatureECDSA.java:112)
	at net.schmizz.sshj.transport.kex.AbstractDHGex.parseGexReply(AbstractDHGex.java:91)
	at net.schmizz.sshj.transport.kex.AbstractDHGex.next(AbstractDHGex.java:58)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:358)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
Exception in thread "main" net.schmizz.sshj.transport.TransportException: Timeout expired
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
	at net.schmizz.concurrent.Event.await(Event.java:105)
	at net.schmizz.sshj.transport.KeyExchanger.waitForDone(KeyExchanger.java:150)
	at net.schmizz.sshj.transport.KeyExchanger.startKex(KeyExchanger.java:145)
	at net.schmizz.sshj.transport.TransportImpl.doKex(TransportImpl.java:259)
	at net.schmizz.sshj.SSHClient.doKex(SSHClient.java:784)
	at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:772)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:127)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:117)
	at org.apache.airavata.helix.agent.sshj.SSHJAgentAdaptor.<init>(SSHJAgentAdaptor.java:70)
	at org.apache.airavata.helix.agent.sshj.SSHJAgentAdaptor.main(SSHJAgentAdaptor.java:129)
Caused by: java.util.concurrent.TimeoutException: Timeout expired

**Comment by hierynomus** [comment]
Are you running in a security sandbox?

**Comment by hierynomus** [comment]
@DImuthuUpe Can you check whether you have the right version of BouncyCastle on the classpath?

**Comment by DImuthuUpe** [comment]
@hierynomus yes there was an old BC jar in the classpath. By removing that fixed the issue. Thank you.
