### ISSUE TITLE
BufferException in Buffer.ensureAvailable

### ISSUE THREAD

**Issue by tmssngr** [hierynomus/sshj#412]
Another user reported following exception:
```
net.schmizz.sshj.common.Buffer$BufferException: Underflow
	at net.schmizz.sshj.common.Buffer.ensureAvailable(Buffer.java:136)
	at net.schmizz.sshj.common.Buffer.readRawBytes(Buffer.java:259)
	at net.schmizz.sshj.common.Buffer.readRawBytes(Buffer.java:254)
	at net.schmizz.sshj.common.Buffer.readBytes(Buffer.java:224)
	at net.schmizz.sshj.common.Buffer.readMPInt(Buffer.java:334)
	at net.schmizz.sshj.common.KeyType$1.readPubKeyFromBuffer(KeyType.java:52)
	at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:464)
	at net.schmizz.sshj.userauth.keyprovider.OpenSSHKeyFile.initPubKey(OpenSSHKeyFile.java:97)
	at net.schmizz.sshj.userauth.keyprovider.OpenSSHKeyFile.init(OpenSSHKeyFile.java:67)
	at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.init(BaseFileKeyProvider.java:55)
	at net.schmizz.sshj.SSHClient.loadKeys(SSHClient.java:569)
	at net.schmizz.sshj.SSHClient.loadKeys(SSHClient.java:538)
	at net.schmizz.sshj.SSHClient.loadKeys(SSHClient.java:587)

```
Again, exceptions caused by wrong user input (file content) never should raise a RuntimeException.

**Comment by hierynomus** [comment]
Is this related to the previous private key issue (#411)?
I disagree here though that the exception from the buffer is unwarranted. What you're actually asking for is that the `initPubKey` should catch the runtime exception and make something nicer out of it.

**Comment by tmssngr** [comment]
Yes, this issue is related. Of course you can implement it as you think.

**Comment by hierynomus** [comment]
@tmssngr The BufferException is not a RuntimeException but a checked exception. However it is logged/handled internally and the library falls back to different behaviour in this case. I will make the logger not log on error level as that indeed is too severe in this case.
