### ISSUE TITLE
NoSuchFieldError initializing CustomNamedCurves

### ISSUE THREAD

**Issue by tmssngr** [hierynomus/sshj#414]
A SmartGit 18.1 user reported following exception on macOS:
```
java.lang.NoSuchFieldError: secp128r1
	at org.bouncycastle.crypto.ec.CustomNamedCurves.<clinit>(Unknown Source)
	at net.schmizz.sshj.transport.kex.Curve25519DH.getCurve25519Params(Curve25519DH.java:60)
	at net.schmizz.sshj.transport.kex.Curve25519SHA256.initDH(Curve25519SHA256.java:44)
	at net.schmizz.sshj.transport.kex.AbstractDHG.init(AbstractDHG.java:46)
	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:230)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:350)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
```
and later (maybe consequential error)
```
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.crypto.ec.CustomNamedCurves
	at net.schmizz.sshj.transport.kex.Curve25519DH.getCurve25519Params(Curve25519DH.java:60)
	at net.schmizz.sshj.transport.kex.Curve25519SHA256.initDH(Curve25519SHA256.java:44)
	at net.schmizz.sshj.transport.kex.AbstractDHG.init(AbstractDHG.java:46)
	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:230)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:350)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
```
Unfortunately, I don't have steps how to reproduce.

**Comment by hierynomus** [comment]
There must be an incompatible BouncyCastle version on the classpath. That is the only explanation I can think of.

**Comment by tmssngr** [comment]
Yes, you are right. After your message I've checked again the log of the user who reported this error and there was and outdated bcprov-jdk15on-*.jar in the system Java's extensions directory. He removed it and it works fine now. I hate it that the system Java's extension directory is used on a Mac even if you are using a private JRE.
