### ISSUE TITLE
Cannot get next power of 2 - exception

### ISSUE THREAD

**Issue by alanroche** [hierynomus/sshj#433]
Getting the following on v 0.21.1

java.lang.IllegalArgumentException: Cannot get next power of 2; 1073745513 is too large
at net.schmizz.sshj.common.Buffer.getNextPowerOf2 (Buffer.java:69)
at net.schmizz.sshj.common.Buffer.ensureCapacity (Buffer.java:142)
at net.schmizz.sshj.common.Buffer.putRawBytes (Buffer.java:270)
at net.schmizz.sshj.connection.channel.ChannelInputStream.receive (ChannelInputStream.java:126)
at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto (AbstractChannel.java:369)
at net.schmizz.sshj.connection.channel.AbstractChannel.handle (AbstractChannel.java:171)
at net.schmizz.sshj.connection.ConnectionImpl.handle (ConnectionImpl.java:130)
at net.schmizz.sshj.transport.TransportImpl.handle (TransportImpl.java:500)
at net.schmizz.sshj.transport.Decoder.decode (Decoder.java:102)
at net.schmizz.sshj.transport.Decoder.received (Decoder.java:170)
at net.schmizz.sshj.transport.Reader.run (Reader.java:59)
[INFO] Disconnected - UNKNOWN
[ERROR] <<chan#0 / close>> woke to: net.schmizz.sshj.connection.ConnectionException: Cannot get next power of 2; 1073745513 is too large
net.schmizz.sshj.connection.ConnectionException: Cannot get next power of 2; 1073745513 is too large
at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)
at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)
at net.schmizz.concurrent.Promise.deliverError(Promise.java:96)
at net.schmizz.concurrent.Event.deliverError(Event.java:74)
at net.schmizz.concurrent.ErrorDeliveryUtil.alertEvents(ErrorDeliveryUtil.java:34)
at net.schmizz.sshj.connection.channel.AbstractChannel.notifyError(AbstractChannel.java:238)
at net.schmizz.sshj.connection.channel.direct.SessionChannel.notifyError(SessionChannel.java:229)
at net.schmizz.sshj.common.ErrorNotifiable$Util.alertAll(ErrorNotifiable.java:35)
at net.schmizz.sshj.connection.ConnectionImpl.notifyError(ConnectionImpl.java:258)
at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:601)
at net.schmizz.sshj.transport.Reader.run(Reader.java:67)
Caused by: net.schmizz.sshj.common.SSHException: Cannot get next power of 2; 1073745513 is too large
at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:36)
at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:29)
at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:595)
... 1 more
Caused by: java.lang.IllegalArgumentException: Cannot get next power of 2; 1073745513 is too large
at net.schmizz.sshj.common.Buffer.getNextPowerOf2(Buffer.java:69)
at net.schmizz.sshj.common.Buffer.ensureCapacity(Buffer.java:142)
at net.schmizz.sshj.common.Buffer.putRawBytes(Buffer.java:270)
at net.schmizz.sshj.connection.channel.ChannelInputStream.receive(ChannelInputStream.java:126)
at net.schmizz.sshj.connection.channel.AbstractChannel.receiveInto(AbstractChannel.java:369)
at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:171)
at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:130)
at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

**Comment by hierynomus** [comment]
Do you have a reproduction scenario? What are you doing when this happens?

**Comment by Stocken** [comment]
This happens when you transmit alot of data in a shell.
E.g. when you run a "cat hugeFile" command.

You only need to call buf.compact() in ChannelInputStream.read when the buffer is too big.
E.g.
           if (buf.rpos() > win.getMaxPacketSize() && buf.available() == 0) {
                buf.clear();
            } else if (buf.rpos() > 10 * 1024 * 1024) {
                buf.compact();
            }

Might be better to just check if buf.rpos() > win.getMaxPacketSize() and do buf.compact() then though.

**Comment by talnicolas** [comment]
I am also facing this issue in v0.27.0 while trying to bring back data through an SSH tunnel. Is there any workaround/fix for this?
