### ISSUE TITLE
net.schmizz.sshj.sftp.SFTPException: No such file

### ISSUE THREAD

**Issue by sibiarunachalam** [hierynomus/sshj#435]
sshj version: 0.21.0
Code:
SSHClient sshClient = new SSHClient();
sshClient.addHostKeyVerifier("hostKeyVerifier");
sshClient.authPassword("username", "password");
sshClient.newSFTPClient().get("dir", "C:\temp");

Exception:
net.schmizz.sshj.sftp.SFTPException: No such file
	at net.schmizz.sshj.sftp.Response.error(Response.java:137)
	at net.schmizz.sshj.sftp.Response.ensurePacketTypeIs(Response.java:114)
	at net.schmizz.sshj.sftp.SFTPEngine.openDir(SFTPEngine.java:161)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Downloader.downloadDir(SFTPFileTransfer.java:119)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Downloader.download(SFTPFileTransfer.java:99)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Downloader.access$300(SFTPFileTransfer.java:90)
	at net.schmizz.sshj.sftp.SFTPFileTransfer.download(SFTPFileTransfer.java:71)
	at net.schmizz.sshj.sftp.SFTPFileTransfer.download(SFTPFileTransfer.java:59)
	at net.schmizz.sshj.sftp.SFTPClient.get(SFTPClient.java:229)

**Comment by sibiarunachalam** [comment]
It looks purely SSH Server configuration problem.
It worked in Windows after set Mount Points in SSH Server

**Comment by sibiarunachalam** [comment]
But, I didn't get any clue for Linux.
It throws same exception when try to get files in "fooDir" in foouser's HOME dir

**Comment by hierynomus** [comment]
I'm not sure I'm following you. Can you write a clear problem description?

**Comment by duelinmarkers** [comment]
Don't know whether this was @sibiarunachalam's issue, as the stack trace is slightly different, and I'm failing to get a regular file, but I just worked through the following thing that sounds similar:

* `sftpClient.put("./local_file.txt", "remote_file.txt")` succeeds.
* The result is that the remote file is in `/somedir/remote_file.txt`, where `/somedir` is the user's default remote working directory.
* `sftpClient.get("remote_file.txt", "./whatever.txt")` fails with `SFTPException: No such file`, stacktrace below.
* `sftpClient.open("remote_file.txt").read(...)` succeeds. *This is what I'm now using.*
* `sftpClient.canonicalize("remote_file.txt")` fails with `SFTPException: No such file`.

In debugging I found that both `canonicalize` and `get` internally result in an attempt to use the path `/remote_file.txt`—note the incorrect leading `/`.

```
net.schmizz.sshj.sftp.SFTPException: No such file

	at net.schmizz.sshj.sftp.Response.error(Response.java:137)
	at net.schmizz.sshj.sftp.Response.ensurePacketTypeIs(Response.java:114)
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:143)
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:149)
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:154)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Downloader.downloadFile(SFTPFileTransfer.java:134)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Downloader.download(SFTPFileTransfer.java:105)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Downloader.access$300(SFTPFileTransfer.java:90)
	at net.schmizz.sshj.sftp.SFTPFileTransfer.download(SFTPFileTransfer.java:71)
	at net.schmizz.sshj.sftp.SFTPFileTransfer.download(SFTPFileTransfer.java:59)
	at net.schmizz.sshj.sftp.SFTPClient.get(SFTPClient.java:229)
```

**Comment by hierynomus** [comment]
Which version are you using?

**Comment by duelinmarkers** [comment]
com.hierynomus:sshj:0.26.0

Also, I found that `./remote_file.txt` works, just not `remote_file.txt`.
