### ISSUE TITLE
com.hierynomus.sshj.transport.DisconnectionTest > shouldNotThrowTimeoutOnDisconnect FAILED

### ISSUE THREAD

**Issue by TukanF1** [hierynomus/sshj#448]
```
D:\Projekty\sshj>gradlew clean build

> Task :compileJava 
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

> Task :compileTestJava 
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Projekty\sshj\src\test\java\com\hierynomus\sshj\test\SshFixture.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

> Task :test 
? Test com.hierynomus.sshj.connection.channel.ChannelCloseEofTest; Executed: 1/1/0t
? Test com.hierynomus.sshj.connection.channel.direct.CommandTest; Executed: 1/1/0
? Test com.hierynomus.sshj.connection.channel.forwarded.RemotePortForwarderTest; Executed: 7/7/0
? Test com.hierynomus.sshj.keepalive.KeepAliveThreadTerminationTest; Executed: 0/0/0
? Test com.hierynomus.sshj.sftp.RemoteFileTest; Executed: 1/1/0

com.hierynomus.sshj.transport.DisconnectionTest > shouldNotThrowTimeoutOnDisconnect FAILED
    net.schmizz.sshj.connection.ConnectionException: Connection reset

        Caused by:
        net.schmizz.sshj.common.SSHException: Connection reset

            Caused by:
            java.net.SocketException: Connection reset
? Test com.hierynomus.sshj.transport.DisconnectionTest; Executed: 5/4/1
? Test com.hierynomus.sshj.transport.kex.KeyExchangeTest; Executed: 5/5/0
? Test com.hierynomus.sshj.userauth.GssApiTest; Executed: 1/1/0
? Test com.hierynomus.sshj.userauth.method.AuthPasswordTest; Executed: 4/4/0
? Test net.schmizz.sshj.common.BufferTest; Executed: 8/8/0
? Test net.schmizz.sshj.keyprovider.KeyProviderUtilTest; Executed: 6/6/0
? Test net.schmizz.sshj.keyprovider.OpenSSHKeyFileTest; Executed: 12/12/0
? Test net.schmizz.sshj.keyprovider.PKCS5KeyFileTest; Executed: 3/3/0
? Test net.schmizz.sshj.keyprovider.PKCS8KeyFileTest; Executed: 2/2/0est
? Test net.schmizz.sshj.keyprovider.PuTTYKeyFileTest; Executed: 6/6/0
? Test net.schmizz.sshj.sftp.FileModeTest; Executed: 2/2/0
? Test net.schmizz.sshj.sftp.PacketReaderTest; Executed: 2/2/0
? Test net.schmizz.sshj.sftp.PathHelperTest; Executed: 7/7/0
? Test net.schmizz.sshj.sftp.SFTPClientTest; Executed: 1/1/0
? Test net.schmizz.sshj.signature.SignatureDSATest; Executed: 1/1/0
? Test net.schmizz.sshj.signature.SignatureECDSATest; Executed: 3/3/0
? Test net.schmizz.sshj.SmokeTest; Executed: 2/2/0
? Test net.schmizz.sshj.transport.mac.BaseMacTest; Executed: 6/6/0
? Test net.schmizz.sshj.transport.mac.HMACMD596Test; Executed: 3/3/0
? Test net.schmizz.sshj.transport.mac.HMACMD5Test; Executed: 3/3/0
? Test net.schmizz.sshj.transport.mac.HMACSHA196Test; Executed: 3/3/0
? Test net.schmizz.sshj.transport.mac.HMACSHA1Test; Executed: 3/3/0
? Test net.schmizz.sshj.transport.mac.HMACSHA2256Test; Executed: 3/3/0
? Test net.schmizz.sshj.transport.mac.HMACSHA2512Test; Executed: 3/3/0
? Test net.schmizz.sshj.util.BufferTest; Executed: 6/6/0
? Test net.schmizz.sshj.xfer.scp.SCPFileTransferTest; Executed: 5/5/0
? Test com.hierynomus.sshj.common.KeyTypeSpec; Executed: 1/1/0
? Test com.hierynomus.sshj.connection.channel.direct.LocalPortForwarderSpec; Executed: 1/1/0
? Test com.hierynomus.sshj.sftp.SFTPClientSpec; Executed: 11/11/0
? Test com.hierynomus.sshj.transport.IdentificationStringParserSpec; Executed: 6/6/0
? Test com.hierynomus.sshj.transport.verification.KnownHostMatchersSpec; Executed: 24/24/0
? Test com.hierynomus.sshj.transport.verification.OpenSSHKnownHostsSpec; Executed: 9/9/0
? Test com.hierynomus.sshj.userauth.keyprovider.FileKeyProviderSpec; Executed: 2/2/0
? Test net.schmizz.sshj.signature.SignatureDSASpec; Executed: 2/2/0
? Test net.schmizz.sshj.transport.verification.FingerprintVerifierSpec; Executed: 6/6/0
? Test net.schmizz.sshj.userauth.password.ConsolePasswordFinderSpec; Executed: 0/0/0
? Test net.schmizz.sshj.xfer.FileSystemFileSpec; Executed: 3/3/0erifierSpec

180 tests completed, 1 failed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///D:/Projekty/sshj/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
15 actionable tasks: 12 executed, 3 up-to-date
```

**Comment by hierynomus** [comment]
@TukanF1 I don't see this test failing (ever) on our CI environment... Is this reproducible for you?

**Comment by TukanF1** [comment]
Every time when I want build SSHJ as separate project in IntelliJ on Windows with Java 8 this test is failed.

**Comment by hierynomus** [comment]
Can you provide the full trace log and stacktrace of that test?

**Comment by TukanF1** [comment]
[build.log](https://github.com/hierynomus/sshj/files/2309119/build.log)
```
D:\Projekty\sshj>gradlew clean build --stacktrace --info > build.log
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Projekty\sshj\src\test\java\com\hierynomus\sshj\test\SshFixture.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

180 tests completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///D:/Projekty/sshj/build/reports/tests/test/index.html

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///D:/Projekty/sshj/build/reports/tests/test/index.html
        at org.gradle.api.tasks.testing.Test.handleTestFailures(Test.java:1446)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:721)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more


* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
```



--------------------------------



[build-debug.log](https://github.com/hierynomus/sshj/files/2309121/build-debug.log)
```
D:\Projekty\sshj>gradlew clean build --stacktrace --debug > build-debug.log
08:11:30.539 [ERROR] [system.err] warning: [options] bootstrap class path not set in conjunction with -source 1.6
08:11:33.146 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
08:11:33.146 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
08:11:33.147 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
08:11:33.147 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
08:11:33.147 [ERROR] [system.err] 1 warning
08:11:36.690 [ERROR] [system.err] warning: [options] bootstrap class path not set in conjunction with -source 1.6
08:11:37.512 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
08:11:37.512 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
08:11:37.512 [ERROR] [system.err] Note: D:\Projekty\sshj\src\test\java\com\hierynomus\sshj\test\SshFixture.java uses unchecked or unsafe operations.
08:11:37.512 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
08:11:37.512 [ERROR] [system.err] 1 warning
08:12:42.377 [ERROR] [org.gradle.api.internal.tasks.testing.logging.TestCountLogger]
180 tests completed, 1 failed
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':test'.
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > There were failing tests. See the report at: file:///D:/Projekty/sshj/build/reports/tests/test/index.html
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
08:12:43.224 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
08:12:43.225 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///D:/Projekty/sshj/build/reports/tests/test/index.html
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.testing.Test.handleTestFailures(Test.java:1446)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.testing.Test.executeTests(Test.java:721)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 29 more
08:12:43.226 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
08:12:43.227 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
08:12:43.227 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
08:12:43.227 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
08:12:43.227 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1m 15s
```

**Comment by TukanF1** [comment]
I want only build *.jar file, cause I need library to SFTP connecting.

**Comment by tancolo** [comment]
@TukanF1  well, you only build *.jar file?  Why not use the lib on maven? As @hierynomus said on #445 

> There is no need to build the library yourself, as it is included in Maven central. Only if you wish to make a PR would you need to be able to build the code.

gradle or pom, any one can be used, right?

Why I want to build sshj lib,  bacause I want to know the workflow, maybe do some modify.
