### ISSUE TITLE
SFTPException: 0xC000007F

### ISSUE THREAD

**Issue by ben-manes** [hierynomus/sshj#456]
I don't know if this is a client or server issue, as the client has worked great overall. I'm currently using `0.26.0` and this is a new sftp integration. Any thoughts before I contact the customer?

```
Caused by: net.schmizz.sshj.sftp.SFTPException: 0xC000007F
        at net.schmizz.sshj.sftp.Response.error(Response.java:137)
        at net.schmizz.sshj.sftp.Response.ensureStatusIs(Response.java:130)
        at net.schmizz.sshj.sftp.Response.ensureStatusPacketIsOK(Response.java:122)
        at net.schmizz.sshj.sftp.RemoteFile.checkWriteResponse(RemoteFile.java:90)
        at net.schmizz.sshj.sftp.RemoteFile.access$000(RemoteFile.java:30)
        at net.schmizz.sshj.sftp.RemoteFile$RemoteFileOutputStream.write(RemoteFile.java:141)
        at net.schmizz.sshj.common.StreamCopier.write(StreamCopier.java:155)
        at net.schmizz.sshj.common.StreamCopier.copy(StreamCopier.java:132)
        at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.uploadFile(SFTPFileTransfer.java:240)
        at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.upload(SFTPFileTransfer.java:186)
        at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.access$100(SFTPFileTransfer.java:166)
        at net.schmizz.sshj.sftp.SFTPFileTransfer.upload(SFTPFileTransfer.java:64)
        at net.schmizz.sshj.sftp.SFTPClient.put(SFTPClient.java:244)
```

**Comment by ben-manes** [comment]
This appears to be a server issue. Not sure if you can get a better error message. The command line client showed,
```
sftp> put /Users/ben/Downloads/test.tiff
Uploading /Users/ben/Downloads/test.tiff to /files/test.tiff
/Users/ben/Downloads/test.tiff                                                                                                         2%   32KB 116.9KB/s   00:11 ETA
Couldn't write to remote file "/files/test.tiff": Failure
```
