### ISSUE TITLE
How to use the default JCE provider in sshj library

### ISSUE THREAD

**Issue by tancolo** [hierynomus/sshj#462]
Hello,

I have a serious problem, the sshj library can no longer be used on Android P.
Using sshj  before Android P is OK.

# Precondition
1. sshj-0.26.0
2. SSH-2.0-OpenSSH_7.6p1
3. Android P

# Key Exception Logs
```
SSH Disconnected due to reason: UNKNOWN, message: The BC provider no longer provides an implementation for MessageDigest.SHA-256.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
( 9426): Exception during connect
( 9426): net.schmizz.sshj.transport.TransportException: The BC provider no longer provides an implementation for MessageDigest.SHA-256.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
( 9426): 	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
( 9426): 	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)
( 9426): 	at net.schmizz.concurrent.Promise.deliverError(Promise.java:95)
( 9426): 	at net.schmizz.concurrent.Event.deliverError(Event.java:74)
( 9426): 	at net.schmizz.concurrent.ErrorDeliveryUtil.alertEvents(ErrorDeliveryUtil.java:34)
( 9426): 	at net.schmizz.sshj.transport.KeyExchanger.notifyError(KeyExchanger.java:392)
( 9426): 	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:600)
( 9426): 	at net.schmizz.sshj.transport.Reader.run(Reader.java:65)

( 9426): Caused by: net.schmizz.sshj.common.SSHException: The BC provider no longer provides an implementation for MessageDigest.SHA-256.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
( 9426): 	at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:36)
( 9426): 	at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:29)
( 9426): 	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:595)
( 9426): 	... 1 more

( 9426): Caused by: net.schmizz.sshj.common.SSHRuntimeException: The BC provider no longer provides an implementation for MessageDigest.SHA-256.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
( 9426): 	at net.schmizz.sshj.transport.digest.BaseDigest.init(BaseDigest.java:59)
( 9426): 	at net.schmizz.sshj.transport.kex.AbstractDHGex.init(AbstractDHGex.java:44)
( 9426): 	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:236)
( 9426): 	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:356)
( 9426): 	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
( 9426): 	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
( 9426): 	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
( 9426): 	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

( 9426): Caused by: java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for MessageDigest.SHA-256.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
( 9426): 	at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:563)
( 9426): 	at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:330)
( 9426): 	at java.security.MessageDigest.getInstance(MessageDigest.java:261)
( 9426): 	at net.schmizz.sshj.common.SecurityUtils.getMessageDigest(SecurityUtils.java:216)
( 9426): 	at net.schmizz.sshj.transport.digest.BaseDigest.init(BaseDigest.java:57)
( 9426): 	... 
```

From the logs, we know that this is due to the modification of certain policies by Android P.
 [Cryptography Changes in Android P](https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html "Cryptography Changes in Android P")

It means, if we specify a provider in sshj `getInstance()` calls,  it will show this exception and sshj will be disconnected. 

# Sshj Code Analysis
From the sshj source code,  I know the workflow of init the Security Provider as follows:
```
@SSHClient.java
public SSHClient() {  
  this(new DefaultConfig());  
}

-> @DefaultConfig.java
public DefaultConfig() {  
  setLoggerFactory(LoggerFactory.DEFAULT);  
  setVersion(readVersionFromProperties());  
 final boolean bouncyCastleRegistered = SecurityUtils.isBouncyCastleRegistered();
 ... ...
}

-> SecurityUtils.java
public static synchronized boolean isBouncyCastleRegistered() {  
    register();  
 return BOUNCY_CASTLE.equals(securityProvider) || SPONGY_CASTLE.equals(securityProvider);  
}

-> SecurityUtils.java
private static void register() {      
...
       registerSecurityProvider("org.bouncycastle.jce.provider.BouncyCastleProvider");  
...
}
```

**Search the entire sshj source code, I can find multiple uses  `getInstance(xxx, provider)`, used to specify BC Provider.**
```
src/main/java/net/schmizz/sshj/userauth/method/AuthGssApiWithMic.java:43:        this(loginContext, mechanismOids, GSSManager.getInstance());
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:87:                MessageDigest.getInstance("MD5", provider);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:88:                KeyAgreement.getInstance("DH", provider);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:106:            return Cipher.getInstance(transformation);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:108:            return Cipher.getInstance(transformation, getSecurityProvider());
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:146:            return KeyAgreement.getInstance(algorithm);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:148:            return KeyAgreement.getInstance(algorithm, getSecurityProvider());
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:163:            return KeyFactory.getInstance(algorithm);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:165:            return KeyFactory.getInstance(algorithm, getSecurityProvider());
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:180:            return KeyPairGenerator.getInstance(algorithm);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:182:            return KeyPairGenerator.getInstance(algorithm, getSecurityProvider());
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:197:            return Mac.getInstance(algorithm);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:199:            return Mac.getInstance(algorithm, getSecurityProvider());
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:214:            return MessageDigest.getInstance(algorithm);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:216:            return MessageDigest.getInstance(algorithm, getSecurityProvider());
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:233:            return Signature.getInstance(algorithm);
src/main/java/net/schmizz/sshj/common/SecurityUtils.java:235:            return Signature.getInstance(algorithm, getSecurityProvider());
src/main/java/net/schmizz/sshj/common/ECDSAVariationsAdapter.java:90:            KeyFactory keyFactory = KeyFactory.getInstance("ECDSA");
```

# Solution (Tring)
I carefully read the information provided by the Android blog and found that it mentioned the use of the default implementation.  [Android Developers Blog](https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html)

> To resolve this, you should stop specifying a provider and use the default implementation.

So I try to use the default implementation. I mean I don't specify a BC provider, follow the workflow of **Register SecurityProvider** 
I just modified this code in 
```
registerSecurityProvider("org.bouncycastle.jce.provider.BouncyCastleProvider");
```
to 
```
registerSecurityProvider("john.org.bouncycastle.jce.provider.BouncyCastleProvider");
```
**john.org.xxx** is a non-existent provider,  so sshj maybe use the default provider, I think.

But unfortunately, the modified sshj lib can not be used, directly reporting an error.
```
[reader] ERROR n.s.sshj.transport.TransportImpl - Dying because - Unable to reach a settlement: [diffie-hellman-group1-sha1, diffie-hellman-group-exchange-sha1] and [curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256, diffie-hellman-group14-sha1]
net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [diffie-hellman-group1-sha1, diffie-hellman-group-exchange-sha1] and [curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256, diffie-hellman-group14-sha1]
	at net.schmizz.sshj.transport.Proposal.firstMatch(Proposal.java:145) ~[sshj-0.26.1-SNAPSHOT.jar:0.26.1-SNAPSHOT]
	at net.schmizz.sshj.transport.Proposal.negotiate(Proposal.java:128) ~[sshj-0.26.1-SNAPSHOT.jar:0.26.1-SNAPSHOT]
	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:224) ~[sshj-0.26.1-SNAPSHOT.jar:0.26.1-SNAPSHOT]
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:356) ~[sshj-0.26.1-SNAPSHOT.jar:0.26.1-SNAPSHOT]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503) ~[sshj-0.26.1-SNAPSHOT.jar:0.26.1-SNAPSHOT]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:103) ~[sshj-0.26.1-SNAPSHOT.jar:0.26.1-SNAPSHOT]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:171) ~[sshj-0.26.1-SNAPSHOT.jar:0.26.1-SNAPSHOT]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59) ~[sshj-0.26.1-SNAPSHOT.jar:0.26.1-SNAPSHOT]
```

Please check the detail log on the attachment (sshj-default-JCE-error.log) if need.

About this error, I find some guy
Regarding the above error, I found that some guys mentioned it in the issue #303, #380
but the answer you gave is as follows:
> There are 2 possibilities:

1.  Have you loaded the unlimited strength java cryptography extensions? If not, then you cannot use anything higher than sha1 encryption. However given the specific combination of KEX algorithms I don't think that is the current problem
2.  Do you have BouncyCastle on the classpath? This specific combination of KEX algorithms is loaded as fallback when BC is not available.

So about the exception of BC Provider, or use the default implementation of Android blog
Do you have any suggestions.

Thank you!

[sshj-default-JCA-error.log](https://github.com/hierynomus/sshj/files/2533881/sshj-default-JCA-error.log)

**Comment by tancolo** [comment]
**The Solution:**
**1. SecurityUtils.java -> registerSecurityProvider()**
``` 
             if (securityProvider == null) {
-                MessageDigest.getInstance("MD5", provider);
-                KeyAgreement.getInstance("DH", provider);
-                setSecurityProvider(provider.getName());
+                MessageDigest.getInstance("MD5");
+                KeyAgreement.getInstance("DH");
+                //setSecurityProvider(provider.getName());
                 return true;
             }
```
It means don't use the BC provider.

**2. PKCS8KeyFile Object**
If you use this code in you android code:
```
PKCS8KeyFile kpcs8 = new PKCS8KeyFile();
kpcs8.init(getPrivateKey(), getPublicKey());
```
you must change this code to 
```
PKCS5KeyFile kpcs5 = new PKCS5KeyFile();
... ...
```
