### ISSUE TITLE
getting exception connecting to SFTP server - PKCS5KeyFile$FormatException: Unrecognized PKCS5 key type: OPENSSH

### ISSUE THREAD

**Issue by rabiori** [hierynomus/sshj#488]
The code is very basic, looks like this:
```
        SSHClient client = new SSHClient();
        client.addHostKeyVerifier(new PromiscuousVerifier());
        client.connect("...");
        String username = "...";
        File privateKey = new File("...");
        KeyProvider keys = client.loadKeys(privateKey.getPath());
        client.authPublickey(username, keys);
```
On the last line, we get an exception:
```
Exception in thread "main" net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:231)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:346)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:365)
        ...
Caused by: net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from PKCS5KeyFile{resource=[PrivateKeyFileResource] ...}
	at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:46)
	at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62)
	at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81)
	at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68)
	at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:72)
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:225)
	... 3 more
Caused by: net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile$FormatException: Unrecognized PKCS5 key type: OPENSSH
	at net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile.readKeyPair(PKCS5KeyFile.java:101)
	at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81)
	at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:44)
	... 8 more
```

The private key file looks like this:
```
-----BEGIN OPENSSH PRIVATE KEY-----
...
-----END OPENSSH PRIVATE KEY-----
```

I saw similar exceptions in past tickets (such as [this](https://github.com/hierynomus/sshj/issues/36)) and I've checked my classpath and I have bouncycastle (1.60).

Any help would be appreciated.

**Comment by rabiori** [comment]
After debugging, I've seen that having the public key in the same directory with ".pub" makes it work - can you please explain a bit?

**Comment by hierynomus** [comment]
Can you try the latest master. I fixed this last week, but haven't released a new version yet.

**Comment by rabiori** [comment]
Sorry, I don't have the time for that currently.
If after you publish a new version you'll want me to test I'll do so happily.

**Comment by hierynomus** [comment]
This is now released in 0.27.0.

**Comment by rabiori** [comment]
indeed fixed, thank you very much!

**Comment by vokod** [comment]
Hello @hierynomus , just a side note: I'm experimenting with your library on android and atlhough I use 0.27.0 I get the exception rabiori mentioned, if there is no public key with ".pub" extension in the same folder as the private key file.  With pub key in place, authentication works.
