### ISSUE TITLE
session.close() hung and taking longer time to close the session.

### ISSUE THREAD

**Issue by tutaidalal** [hierynomus/sshj#510]
I am running a tail command on a file. The tail command does not have any output as there is no chnages in the file. After some time when I am trying to close the session using session.close it is taking around 30000 MS return the control to mu code and I am getting an exceptation - 

session channel: id=2, recipient=1, localWin=[winSize=2097089], remoteWin=[winSize=2097152] >, Error net.schmizz.sshj.connection.ConnectionException: Timeout expired

It is delaying my entire framework and the socket are not getting closed properly.

**Comment by tutaidalal** [comment]
below is the complete stack Trace - 

12:35:44.405 TRACE - Closing session < session channel: id=2, recipient=1, localWin=[winSize=2097089], remoteWin=[winSize=2097152] >
12:35:44.405 DEBUG - Sending close
12:35:44.405 TRACE - Encoding packet #18: 61 00 00 00 01
12:35:44.406 DEBUG - Awaiting <<chan#2 / close>>
2019-05-10 12:36:14,412 ERROR c.c.d.s.c.pool.SSHSessionPool- Unable to close session < session channel: id=2, recipient=1, localWin=[winSize=2097089], remoteWin=[winSize=2097152] >, Error net.schmizz.sshj.connection.ConnectionException: Timeout expired
net.schmizz.sshj.connection.ConnectionException: Timeout expired
	at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)
	at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
	at net.schmizz.concurrent.Event.await(Event.java:105)
	at net.schmizz.sshj.connection.channel.AbstractChannel.close(AbstractChannel.java:266)
	at com.ci.driver.ssh.connection.pool.SSHSessionPool.releaseSession(SSHSessionPool.java:428)
	at com.ci.driver.logging.driver.SSHLogCollector.closeInputResources(SSHLogCollector.java:177)
	at com.ci.driver.logging.driver.SSHLogCollector.endFeatureFile(SSHLogCollector.java:279)
	at com.ci.driver.logging.service.LoggingService.stopCaptureAll(LoggingService.java:236)
	at com.ci.driver.logging.service.LoggingService.tearDownAfterFeature(LoggingService.java:508)
	at com.ci.driver.common.service.DriverTearDownHelper.call(DriverTearDownHelper.java:47)
	at com.ci.driver.common.service.DriverTearDownHelper.call(DriverTearDownHelper.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Timeout expired
	... 14 more
TIME TAKEN TO RELEASE SESSION : 30008 MS

**Comment by tutaidalal** [comment]
The command I am trying to execute - 

tail -f -n <line number> <file name>
