### ISSUE TITLE
Curve25519 - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by tagus24** [hierynomus/sshj#519]
Hi,

When running a program in a linux machine with Curve25519 being negotiated, I'm getting the following error:

2019-07-06 08:05:26 [reader] DEBUG n.s.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
2019-07-06 08:05:26 [reader] DEBUG n.s.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=curve25519-sha256; sig=ssh-ed25519; c2sCipher=aes128-ctr; s2cCipher=aes128-ctr; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
Exception in thread "reader" java.lang.NoSuchMethodError: org.bouncycastle.math.ec.ECCurve.<init>(Lorg/bouncycastle/math/field/FiniteField;)V
        at org.bouncycastle.math.ec.ECCurve$AbstractFp.<init>(Unknown Source)
        at org.bouncycastle.math.ec.custom.djb.Curve25519.<init>(Unknown Source)
        at org.bouncycastle.crypto.ec.CustomNamedCurves$1.createParameters(Unknown Source)
        at org.bouncycastle.asn1.x9.X9ECParametersHolder.getParameters(Unknown Source)
        at org.bouncycastle.crypto.ec.CustomNamedCurves.getByName(Unknown Source)
        at net.schmizz.sshj.transport.kex.Curve25519DH.getCurve25519Params(Curve25519DH.java:60)
        at net.schmizz.sshj.transport.kex.Curve25519SHA256.initDH(Curve25519SHA256.java:59)
        at net.schmizz.sshj.transport.kex.AbstractDHG.init(AbstractDHG.java:46)
        at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:236)
        at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:356)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
        at net.schmizz.sshj.transport.Decoder.decodeMte(Decoder.java:159)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:79)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:231)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

The same runs successfully in windows machine but, here, is not using curve25519-sha256:
2019-07-06 11:03:37 [reader] DEBUG n.s.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=diffie-hellman-group1-sha1; sig=ssh-ed25519; c2sCipher=aes128-ctr; s2cCipher=aes128-ctr; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]

I'm using in my project:

<dependency>
	    <groupId>com.hierynomus</groupId>
	    <artifactId>sshj</artifactId>
	    <version>0.27.0</version>
	</dependency>

**Comment by hierynomus** [comment]
Most probably the version of BouncyCastly you're using is no longer compatible. Have you tried running with the version with which sshjj was compiled?

**Comment by tagus24** [comment]
I tried with bouncycastle 1.60 too but no lucky. Same error happened.
I solved my problem, creating a custom ConfigImpl without the Curve KeyExchangeFactory.
(I'm not only sure why in my case is happening the issue but, If I'm the only one getting it, is something that I should be missing).
