### ISSUE TITLE
Getting Error Exhausted available authentication methods

### ISSUE THREAD

**Issue by Pavan-Savlani** [hierynomus/sshj#525]
Hi,
I need your help on the below issue.
I'm getting "Error Exhausted available authentication methods".
I'm trying to connect to channel advisor for SFTP. I'm also using a proxy for this. The problem is, When I run this code, it throws the error "Exhausted available authentication methods". 
Channel Advisor uses id and password auth method for sftp, and moreover I just want avoid host key verification. Here is my code below:

`
import net.schmizz.sshj.Config;
import net.schmizz.sshj.DefaultConfig;
import net.schmizz.sshj.SSHClient;
import net.schmizz.sshj.sftp.SFTPClient;
import net.schmizz.sshj.signature.SignatureDSA;
import net.schmizz.sshj.signature.SignatureECDSA;
import net.schmizz.sshj.signature.SignatureRSA;
import net.schmizz.sshj.transport.verification.HostKeyVerifier;
import net.schmizz.sshj.transport.verification.PromiscuousVerifier;
import net.schmizz.sshj.userauth.method.AuthPassword;
import net.schmizz.sshj.userauth.password.PasswordFinder;
import net.schmizz.sshj.userauth.password.PasswordUtils;
import net.schmizz.sshj.xfer.FileSystemFile;

import java.io.File;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.SocketAddress;
import java.security.PublicKey;
import net.schmizz.sshj.Config;
import net.schmizz.sshj.DefaultConfig;
import net.schmizz.sshj.SSHClient;
import net.schmizz.sshj.sftp.SFTPClient;
import net.schmizz.sshj.signature.SignatureDSA;
import net.schmizz.sshj.signature.SignatureECDSA;
import net.schmizz.sshj.signature.SignatureRSA;
import net.schmizz.sshj.transport.verification.HostKeyVerifier;
import net.schmizz.sshj.transport.verification.PromiscuousVerifier;
import net.schmizz.sshj.userauth.method.AuthPassword;
import net.schmizz.sshj.userauth.password.PasswordFinder;
import net.schmizz.sshj.userauth.password.PasswordUtils;
import net.schmizz.sshj.xfer.FileSystemFile;

import java.io.File;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.SocketAddress;
import java.security.PublicKey;

import com.hierynomus.sshj.signature.SignatureEdDSA;

/** This example demonstrates uploading of a file over SFTP to the SSH server. */
public class SFTPUpload {
	private static String proxyHost = "proxy.abc.com";
    private static int proxyPort = 80;
    static SocketAddress addr = new InetSocketAddress(proxyHost, proxyPort);
    static Proxy proxy = new Proxy(Proxy.Type.HTTP, addr);
    
    public static void main(String[] args)
            throws IOException {
        
    	Config config = new DefaultConfig();
    	final SSHClient ssh = new SSHClient(config);
    	ssh.addHostKeyVerifier(new PromiscuousVerifier());
        
        try{
           	ssh.connect("sftp.ChannelAdvisor.com",22,proxy);
        }
		catch(Exception e) {
        	e.printStackTrace();
		}
        
        if(ssh.isConnected())
        	System.out.println("connected");
        try {
        	
            String password = "Abc123";
            PasswordFinder createOneOff = PasswordUtils.createOneOff(password.toCharArray());
			ssh.auth("fffgrr123456jjj123456j33445677jh", new AuthPassword(createOneOff));
            			
			if (ssh.isAuthenticated()) {
        		System.out.println("Auth");}
        	else 
        		System.out.println("NO_Auth");
        } finally {
            ssh.disconnect();
        }
    }
}

`

Here are the logs:
`
log4j:WARN No appenders could be found for logger (net.schmizz.sshj.transport.random.BouncyCastleRandom).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
connected
Exception in thread "main" net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:205)
	at SFTPUpload.main(SFTPUpload.java:61)
`

**Comment by Pavan-Savlani** [comment]
I was using wrong account id, hence it was throwing the above error. Now it works fine.
