### ISSUE TITLE
Error during opening file: java.lang.ArrayIndexOutOfBoundsException: arraycopy: destination index -4 out of bounds for byte[256]

### ISSUE THREAD

**Issue by taras19921** [hierynomus/sshj#532]
During opening the file in this way :

`RemoteFile remoteFile = sftpClient.open(path)`

I've faced with following error with stacktrace:

>  java.lang.ArrayIndexOutOfBoundsException: arraycopy: destination index -4 out of bounds for byte[256]
	at net.schmizz.sshj.common.Buffer.putRawBytes(Buffer.java:271)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.write(ChannelOutputStream.java:64)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:141)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:131)
	at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:292)
	at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:130)
	at net.schmizz.sshj.sftp.SFTPEngine.doRequest(SFTPEngine.java:136)
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:141)
	at net.schmizz.sshj.sftp.SFTPClient.open(SFTPClient.java:68)
	at net.schmizz.sshj.sftp.SFTPClient.open(SFTPClient.java:73)
	at net.schmizz.sshj.sftp.SFTPClient.open(SFTPClient.java:78)
	at com.echovox.paidle.common.util.SftpUtil.getFileDataListFromZip(SftpUtil.java:86)
	at com.echovox.paidle.common.util.SftpUtil.lambda$getFileDataWithRetry$1(SftpUtil.java:139)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

I found 3 implementation of `open` method:

`public RemoteFile open(String filename)`
`public RemoteFile open(String filename, Set<OpenMode> mode)`
`public RemoteFile open(String filename, Set<OpenMode> mode, FileAttributes attrs)`

Is it possible to use somehow `Set<OpenMode> mode` and/or `FileAttributes attrs` to avoid this issue?

**Comment by diykorey** [comment]
same for me
Stacktrace
java.lang.ArrayIndexOutOfBoundsException: arraycopy: destination index -4 out of bounds for byte[256]
	at java.base/java.lang.System.arraycopy(Native Method)
	at net.schmizz.sshj.common.Buffer.putRawBytes(Buffer.java:271)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.write(ChannelOutputStream.java:64)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:141)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:131)
	at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:292)
	at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:130)
	at net.schmizz.sshj.sftp.SFTPEngine.doRequest(SFTPEngine.java:136)
	at net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:263)
	at net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:217)
	at net.schmizz.sshj.sftp.SFTPFileTransfer.download(SFTPFileTransfer.java:70)
	at net.schmizz.sshj.sftp.SFTPClient.get(SFTPClient.java:239)

**Comment by weronika-redlarska** [comment]
Hi, same issue here. So far it happened only once, but retrying to upload the same file kept resulting in the same error. The issue did not persist after restarting the app.

`Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: destination index -4 out of bounds for byte[1024]
	at java.base/java.lang.System.arraycopy(Native Method)
	at net.schmizz.sshj.common.Buffer.putRawBytes(Buffer.java:271)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.write(ChannelOutputStream.java:64)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:141)
	at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:131)
	at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:292)
	at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:130)
	at net.schmizz.sshj.sftp.SFTPEngine.doRequest(SFTPEngine.java:136)
	at net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:263)
	at net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:217)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.isDirectory(SFTPFileTransfer.java:285)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.upload(SFTPFileTransfer.java:181)
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.access$100(SFTPFileTransfer.java:166)
	at net.schmizz.sshj.sftp.SFTPFileTransfer.upload(SFTPFileTransfer.java:64)
	at net.schmizz.sshj.sftp.SFTPClient.put(SFTPClient.java:244)`

**Comment by zzheffn** [comment]
Hi, same issue here. It happens when I tried to send around 400 files to remote SFTP server using a same SFTPClient.

`java.lang.ArrayIndexOutOfBoundsException at java.lang.System.arraycopy(Native Method) at net.schmizz.sshj.common.Buffer.putRawBytes(Buffer.java:271) at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.write(ChannelOutputStream.java:64) at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:141) at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:131) at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:292) at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:130) at net.schmizz.sshj.sftp.SFTPEngine.doRequest(SFTPEngine.java:136) at net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:263) at net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:217) at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.isDirectory(SFTPFileTransfer.java:285) at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.upload(SFTPFileTransfer.java:181) at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.access$100(SFTPFileTransfer.java:166) at net.schmizz.sshj.sftp.SFTPFileTransfer.upload(SFTPFileTransfer.java:64) at net.schmizz.sshj.sftp.SFTPClient.put(SFTPClient.java:244) at `

**Comment by zhanghai** [comment]
Same for me:

```
    java.lang.ArrayIndexOutOfBoundsException: src.length=1 srcPos=0 dst.length=256 dstPos=-4 length=1
        at java.lang.System.arraycopy(System.java:527)
        at net.schmizz.sshj.common.Buffer.putRawBytes(Buffer.java:272)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.write(ChannelOutputStream.java:65)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:143)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream.write(ChannelOutputStream.java:133)
        at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:306)
        at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:138)
        at net.schmizz.sshj.sftp.SFTPEngine.doRequest(SFTPEngine.java:144)
        at net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:277)
        at net.schmizz.sshj.sftp.SFTPEngine.lstat(SFTPEngine.java:230)
        at net.schmizz.sshj.sftp.SFTPClient.lstat(SFTPClient.java:198)
...
```

**Comment by zhanghai** [comment]
Obtained another stacktrace but this time with an index of `-5`:

```
    java.lang.ArrayIndexOutOfBoundsException: length=256; index=-5
        at net.schmizz.sshj.common.Buffer.putUInt32(Buffer.java:338)
        at net.schmizz.sshj.transport.Encoder.encode(Encoder.java:109)
        at net.schmizz.sshj.transport.TransportImpl.write(TransportImpl.java:421)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.flush(ChannelOutputStream.java:103)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.flush(ChannelOutputStream.java:71)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream.flush(ChannelOutputStream.java:183)
        at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:311)
        at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:138)
        at net.schmizz.sshj.sftp.SFTPEngine.doRequest(SFTPEngine.java:144)
        at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:149)
        at net.schmizz.sshj.sftp.SFTPClient.open(SFTPClient.java:68)
...
```

Looking at the code, it seems that the `Encoder` code is setting a negative `wpos()` with its `startOfPacket`:

https://github.com/hierynomus/sshj/blob/69812e9a818701fd906852f03b3eb44ea5651f7b/src/main/java/net/schmizz/sshj/transport/Encoder.java#L107-L109

which is calculated at:

https://github.com/hierynomus/sshj/blob/69812e9a818701fd906852f03b3eb44ea5651f7b/src/main/java/net/schmizz/sshj/transport/Encoder.java#L89

However, I don't have the knowledge of how this is supposed to be calculated. @hierynomus, could you kindly take a look?

**Comment by vladimirlagunov** [comment]
According to my experience, this error is thrown when trying to read from a closed TCP socket. If I remember my old investigations correctly, an instance of `TransportException` always preceeds `ArrayIndexOutOfBoundException`. So, ensure that you catch `TransportException` and stop any usage of the connection after receiving it.

Also, I tried to fix this error a while ago, but didn't find a laconic solution.
