### ISSUE TITLE
[Windows] Unable to reach a settlement

### ISSUE THREAD

**Issue by aditi-agarwal-tw** [hierynomus/sshj#538]
Hello my shaded jar with SSHJ connects on a macOS machine with no issues. 
When I run the same jar on Windows Server 2016, I get a unable to reach settlement error. I have installed the JCE jars, but it did not help.

**Comment by aditi-agarwal-tw** [comment]
The errors further indicate that the BouncyCastle provider could not be registered. I am using JDK11

**Comment by hierynomus** [comment]
Shaded jars do not work due to missing jar signatures.

**Comment by siddarthshahtw** [comment]
Hi @hierynomus we were able to by pass the error for bouncy castle by excluding the BC jar during shading, and are able to set BC as the security provider. Post this the sftp connection fails giving the following error

`Exception in thread "reader" java.lang.NoClassDefFoundError: org/bouncycastle/crypto/ec/CustomNamedCurves
        at net.schmizz.sshj.transport.kex.Curve25519DH.getCurve25519Params(Curve25519DH.java:60)
        at net.schmizz.sshj.transport.kex.Curve25519SHA256.initDH(Curve25519SHA256.java:59)
        at net.schmizz.sshj.transport.kex.AbstractDHG.init(AbstractDHG.java:46)
        at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:236)
        at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:356)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
        at net.schmizz.sshj.transport.Decoder.decodeMte(Decoder.java:159)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:79)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:231)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.crypto.ec.CustomNamedCurves
`
On seeing the github repo for net.schmizz.sshj.transport.kex.Curve25519DH.getCurve25519Params we found a TODO comment for BouncyCastle. Can you please let us know if that is indeed the case or any changes / workarounds that we could do?

Thanks
