### ISSUE TITLE
KeyExchange signature verification failed Exception

### ISSUE THREAD

**Issue by anujkhandelwal1990** [hierynomus/sshj#541]
Hi,

I am getting below error when trying to establish connectivity with a SFTP server via SSHJ library, however the same connectivity is working fine from unix command (sftp -v username@serveraddress).  Can someone explain me what could cause this in the library ?

Thanks,
Anuj

net.schmizz.sshj.transport.TransportException: [KEY_EXCHANGE_FAILED] KeyExchange signature verification failed         at net.schmizz.sshj.transport.kex.AbstractDHGex.parseGexReply(AbstractDHGex.java:92)         at net.schmizz.sshj.transport.kex.AbstractDHGex.next(AbstractDHGex.java:58)         at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:358)         at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)         at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)         at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)         at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

**Comment by hierynomus** [comment]
Can you provide more logging? Preferably debug or trace level.
