### ISSUE TITLE
Does sshj conflict with jdk8?

### ISSUE THREAD

**Issue by heroXin2019** [hierynomus/sshj#551]
![1579143487(1)](https://user-images.githubusercontent.com/50572335/72489513-433f1180-384f-11ea-99ae-29e45d71a126.jpg)
![1579143522(1)](https://user-images.githubusercontent.com/50572335/72489514-433f1180-384f-11ea-8c85-2603f57b976d.jpg)

**Comment by heroXin2019** [comment]
Exception in thread "reader" java.lang.NoSuchMethodError: org.bouncycastle.math.ec.ECCurve.<init>(Lorg/bouncycastle/math/field/FiniteField;)V
	at org.bouncycastle.math.ec.ECCurve$AbstractFp.<init>(Unknown Source)
	at org.bouncycastle.math.ec.custom.djb.Curve25519.<init>(Unknown Source)
	at org.bouncycastle.crypto.ec.CustomNamedCurves$1.createParameters(Unknown Source)
	at org.bouncycastle.asn1.x9.X9ECParametersHolder.getParameters(Unknown Source)
	at org.bouncycastle.crypto.ec.CustomNamedCurves.getByName(Unknown Source)
	at net.schmizz.sshj.transport.kex.Curve25519DH.getCurve25519Params(Curve25519DH.java:60)
	at net.schmizz.sshj.transport.kex.Curve25519SHA256.initDH(Curve25519SHA256.java:44)
	at net.schmizz.sshj.transport.kex.AbstractDHG.init(AbstractDHG.java:46)
	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:236)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:356)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

**Comment by hierynomus** [comment]
bcprov is not a standard part of the JRE/JDK. Also the `jre/ext/lib` directory normally does not contain that many jar files. Those should typically not be present.

**Comment by hierynomus** [comment]
@heroXin2019 Does this answer your question?

**Comment by nikunjbpatel** [comment]
I have same problem...jre/lib/ext has bcprov-jdk16-146 exists into and latest sshj is using bcprov-jdk15on-1.68. Getting following exception. if i remove bcprov jar file from .jre/lib/ext it works fine.
net.schmizz.sshj.transport.TransportException: Timeout expired
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)

**Comment by hierynomus** [comment]
See my answer above, if you're adding those jars to your `jre/ext/lib` directory, you're asking for problems

**Comment by povorozniuk** [comment]
Yeah.. this is due to the fact that even the latest version of "sshj" is not using up-to-date bouncy castle jars (jdk16). In my case, I implemented PGP encryption using

```
<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcpg-jdk16</artifactId>
			<version>1.46</version>
</dependency>
```

and the sshj started throwing the same exception you are seeing.



This is the dependency tree from the latest sshj library. I will probably use "commons-vfs2" for the sftp file transfer instead of sshj since otherwise I will have to go down from "bcpg-jdk16" for encryption to "bcpg-jdk15on"

```
 +- com.hierynomus:sshj:jar:0.31.0:compile
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.68:runtime
[INFO] |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.68:runtime
[INFO] |  +- com.jcraft:jzlib:jar:1.1.3:runtime
[INFO] |  +- com.hierynomus:asn-one:jar:0.5.0:runtime
[INFO] |  \- net.i2p.crypto:eddsa:jar:0.3.0:runtime
```

**Comment by hierynomus** [comment]
Answered I think.
