### ISSUE TITLE
Groovy script calling sshClient returns invalid chars

### ISSUE THREAD

**Issue by AlvinChacko** [hierynomus/sshj#571]
Im not sure if I should post this here but Im using sshj to connect to a remote client. I have the following in my groovy script:

@Grab(group='com.hierynomus', module='sshj', version='0.27.0')
@Grab(group='org.slf4j', module='slf4j-api', version='1.7.30')
@Grab(group='org.slf4j', module='slf4j-simple', version='1.7.30')

But on my machine, I get some invalid chars when opening the sshClient:
net.schmizz.sshj.transport.TransportException: Server does not support SSHv2, identified as: **????|??>???^?**
	at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:181)
	at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:769)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:127)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:117)
	at net.schmizz.sshj.SocketClient$connect.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

I traced the code back to  sshj/src/main/java/com/hierynomus/sshj/transport/IdentificationStringParser.java but Im not sure what the encoding issues. Im running this on z/os unix environment using the groovy command:
groovy -c ISO8859-1 file

**Comment by hierynomus** [comment]
Have you tried `-c UTF-8`

**Comment by AlvinChacko** [comment]
Yes I tried that as well
