### ISSUE TITLE
SCPException: Received unknown response code with atmoz/sftp docker image

### ISSUE THREAD

**Issue by mmartsen** [hierynomus/sshj#578]
Hello, 

Im receiving following exception while doing scp upload/download (simple code like `ssh.newSCPFileTransfer().upload(localPath, remotePath)`) with pure https://hub.docker.com/r/atmoz/sftp image. 

       `net.schmizz.sshj.xfer.scp.SCPException: Received unknown response code
        at net.schmizz.sshj.xfer.scp.SCPEngine.check(SCPEngine.java:75)
        at net.schmizz.sshj.xfer.scp.SCPUploadClient.startCopy(SCPUploadClient.java:69)
        at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:50)
        at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:43)
        at net.schmizz.sshj.xfer.scp.SCPFileTransfer.upload(SCPFileTransfer.java:55)`

Exception is thrown, despite the file is being copied successfully. Maybe it's somehow related to some additional shell output of the image, but i can't find anything

**Comment by hierynomus** [comment]
Have you tried with SFTP instead of SCP?

**Comment by mmartsen** [comment]
> Have you tried with SFTP instead of SCP?

Yes, SFTP transfer works fine

**Comment by adamlwgriffiths** [comment]
SCP fails if the shell echos anything out during login (ie inside `.bashrc`)
https://stackoverflow.com/a/12442753/1591957

Solution is to remove or suppress output to stdout with a check if it's a real TTY: `if [ -t 0 ]; then ...`. (taken from the SO answer above)
