### ISSUE TITLE
Connecting to cisco NCS 4016 fails during the shell creation

### ISSUE THREAD

**Issue by srikarn** [hierynomus/sshj#621]
If I do regular ssh, it works fine

```09:30:37.611 [connects-1] WARN  c.h.s.t.IdentificationStringParser - Server identification has bad line ending, was expecting a '\r\n' however got: '0' (hex: 30) 
09:30:37.614 [connects-1] WARN  c.h.s.t.IdentificationStringParser - Will treat the identification of this server 'SSH-2.0-Cisco-2.0' leniently 
09:30:37.615 [connects-1] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `null` 
09:30:37.624 [connects-1] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `SOME` 
09:30:37.624 [connects-1] DEBUG net.schmizz.concurrent.Promise - Awaiting <<kex done>> 
09:30:38.311 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `null` 
09:30:38.311 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `SOME` 
09:30:38.312 [connects-1] DEBUG net.schmizz.concurrent.Promise - Setting <<service accept>> to `null` 
09:30:38.312 [connects-1] DEBUG net.schmizz.concurrent.Promise - Awaiting <<service accept>> 
09:30:38.725 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<service accept>> to `SOME` 
09:30:38.726 [connects-1] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `null` 
09:30:38.726 [connects-1] DEBUG net.schmizz.concurrent.Promise - Awaiting <<authenticated>> 
09:30:38.828 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `false` 
09:30:38.829 [connects-1] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `null` 
09:30:38.829 [connects-1] DEBUG net.schmizz.concurrent.Promise - Awaiting <<authenticated>> 
09:30:38.968 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `true` 
09:30:38.976 [connects-1] DEBUG net.schmizz.concurrent.Promise - Awaiting <<chan#0 / open>> 
09:30:39.070 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<chan#0 / open>> to `SOME` 
09:30:39.070 [connects-1] DEBUG net.schmizz.concurrent.Promise - Awaiting <<chan#0 / chanreq for shell>> 
09:30:39.169 [reader] ERROR n.s.sshj.transport.TransportImpl - Dying because -  
net.schmizz.sshj.transport.TransportException: 
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:554)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:513)
	at net.schmizz.sshj.transport.Decoder.decodeMte(Decoder.java:159)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:79)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:231)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
09:30:39.170 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<chan#0 / close>> to `SOME` 
09:30:39.170 [connects-1] ERROR net.schmizz.concurrent.Promise - <<chan#0 / chanreq for shell>> woke to: net.schmizz.sshj.connection.ConnectionException 
09:30:39.172 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<transport close>> to `SOME` 
```

**Comment by hierynomus** [comment]
Is this the same issue as #624?
