### ISSUE TITLE
How to Connect when host requires aes128cbc or some algorithm/cipher to get access?

### ISSUE THREAD

**Issue by dgallego58** [hierynomus/sshj#639]
for example:
i'm trying to execute this command with the host IP:

in terminal i do this:

`sftp -c aes128-cbc -oPort=9999 myUser@194.0.5.96 `//just a random ip and port for this example

then put my password, and thats all i get the access.

i'm trying this to do what i did above but i cant get access.

```
 Config config = new DefaultConfig();
        List<Factory.Named<Cipher>> cipherList = new ArrayList<>();
        Factory.Named<Cipher> aes128Cbc = BlockCiphers.AES128CBC();

        cipherList.add(aes128Cbc);
        config.setCipherFactories(cipherList);


        try (SSHClient sshClient = new SSHClient(config)) {
            sshClient.addHostKeyVerifier(new PromiscuousVerifier());
            sshClient.connect(host, port);
            sshClient.authPassword(user, PasswordUtils.createOneOff(pass.toCharArray()));
            LOGGER.info(
                    "===== Connecting to Bank SFTP: Connected? " + sshClient.isConnected() + " Authenticated? " + sshClient
                            .isAuthenticated());


            sshClient.startSession();
            return sshClient;
        }
```
but im not sure if im doing it right.

**Comment by dgallego58** [comment]
no answer? :C how can i configure a specific Cipher to establish connection?

**Comment by hierynomus** [comment]
What is happening then that you cannot get access?

The code looks good.

**Comment by dgallego58** [comment]
when connection starts and it says that im connected and authenticated, but inmediatly when i do a put via sftp, it throw it down, 

below is the stack trace, as you can see the connection says it is true and im authenticated, but when i do a put, like this

`public void uploadAndSendFile(String localDirWithFile, String remoteDirWithFileName) {
         LOGGER.info("===== UPLOADING FILES FROM: " + localDirWithFile + " as " + remoteDirWithFileName);
         try (SSHClient sshClient = bankSession(); SFTPClient sftpClient = sshClient.newSFTPClient()) {
             LOGGER.info("===== Starting Upload");
             //checkout with care if the remote dir is / or */**
             sftpClient.put(localDirWithFile, remoteDirWithFileName);
             sshClient.disconnect();
         } catch (IOException | NullPointerException e) {
 
             LOGGER.error("==== Error on upload file: " + e.getMessage());
             AwsAlarmThrower.sendSftpErrorUploadAlarm();
         }
     }`

`2020-10-19 14:40:00.894  INFO 7 --- [   MetroBatch-4] n.s.sshj.transport.random.JCERandom      : Creating new SecureRandom.
2020-10-19 14:40:00.989  INFO 7 --- [   MetroBatch-4] n.schmizz.sshj.transport.TransportImpl   : Client identity string: SSH-2.0-SSHJ_0.30.0
2020-10-19 14:40:01.052  INFO 7 --- [   MetroBatch-4] n.schmizz.sshj.transport.TransportImpl   : Server identity string: SSH-2.0-GoAnywhere6.2.3
2020-10-19 14:40:01.589  INFO 7 --- [   MetroBatch-4] c.a.metro.batch.service.SftpService      : ===== Connecting to Bank SFTP: Connected? true Authenticated? true
2020-10-19 14:40:01.689  INFO 7 --- [   MetroBatch-4] n.schmizz.sshj.transport.TransportImpl   : Disconnected - BY_APPLICATION
2020-10-19 14:40:01.708 ERROR 7 --- [   MetroBatch-4] o.s.batch.core.step.AbstractStep         : Encountered an error executing step recyclerStep2 in job recyclerOutPutFileJob
java.lang.IllegalStateException: Not connected
	at net.schmizz.sshj.SSHClient.checkConnected(SSHClient.java:823) ~[sshj-0.30.0.jar!/:0.30.0]
	at net.schmizz.sshj.SSHClient.newSFTPClient(SSHClient.java:720) ~[sshj-0.30.0.jar!/:0.30.0]
	at com.aliados.metro.batch.service.SftpService.uploadAndSendFile(SftpService.java:108) ~[classes!/:na]
	at com.aliados.metro.batch.task.RecyclerUploadTasklet.execute(RecyclerUploadTasklet.java:41) ~[classes!/:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406) ~[spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330) ~[spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272) ~[spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81) ~[spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257) ~[spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200) ~[spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:66) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:136) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:308) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:144) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) [spring-core-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:137) [spring-batch-core-4.0.2.RELEASE.jar!/:4.0.2.RELEASE]
	at com.aliados.metro.batch.service.SchedulerService.outputRecyclerJob(SchedulerService.java:90) [classes!/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) ~[spring-context-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]`

**Comment by hierynomus** [comment]
Do you also have DEBUG level logging for SSHJ? ANd what does the server log?
