### ISSUE TITLE
Unable to reach a settlement: [diffie-hellman-group1-sha1, diffie-hellman-group-exchange-sha1] and [ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group14-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512]

### ISSUE THREAD

**Issue by jeffschnellerEnvisa** [hierynomus/sshj#644]
Trying to use a puTTY key.  Here is the error and stack trace:
`net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [diffie-hellman-group1-sha1, diffie-hellman-group-exchange-sha1] and [ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group14-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512]
	at net.schmizz.sshj.transport.Proposal.firstMatch(Proposal.java:149)
	at net.schmizz.sshj.transport.Proposal.negotiate(Proposal.java:130)
	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:223)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:517)
	at net.schmizz.sshj.transport.Decoder.decodeMte(Decoder.java:159)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:79)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:231)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
`

I am running jdk_1.8.0_191 so the JCE higher level is already included.  The putty key works as I use it to connect through winscp gui with no issues.  Is there anything that I am missing?

My pom has:
`	<dependency>
	  <groupId>com.hierynomus</groupId>
	  <artifactId>sshj</artifactId>
	  <version>0.30.0</version>
	</dependency>
	<dependency>
	    <groupId>org.bouncycastle</groupId>
	    <artifactId>bcprov-jdk15on</artifactId>
	    <version>1.66</version>
	</dependency>	
	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bcpkix-jdk15on</artifactId>
		<version>1.66</version>
	</dependency>
	<dependency>
	    <groupId>net.i2p.crypto</groupId>
	    <artifactId>eddsa</artifactId>
	    <version>0.3.0</version>
	</dependency>
	<dependency>
	    <groupId>com.hierynomus</groupId>
	    <artifactId>asn-one</artifactId>
	    <version>0.4.0</version>
	</dependency>
	<dependency>
    	<groupId>com.jcraft</groupId>
    	<artifactId>jzlib</artifactId>
    	<version>1.1.3</version>
	</dependency>`

**Comment by hierynomus** [comment]
Have you registered the BouncyCastle SecurityProvider?

**Comment by hierynomus** [comment]
@jeffschnellerEnvisa Have you solved your issue?

**Comment by hierynomus** [comment]
Closing due to inactivity
