### ISSUE TITLE
Same code and certificate fails on Linux

### ISSUE THREAD

**Issue by splat-man** [hierynomus/sshj#671]
I run the exact same code and use the exact same key on my Windows desktop and it is all successful, but when I execute on Linux(Centos 7.5.1804) it fails with the output listed below. Any help or insight would be appreciated.

I have attached the test key with a gif extension so that it can be looked at, in case that helps with identifying the issue.

Code Used:
                        ssh = new SSHClient();
			Security.addProvider(new BouncyCastleProvider());
			ssh.addHostKeyVerifier(new PromiscuousVerifier());
			ssh.connect(hostedAddress);
			ssh.authPublickey("customer105115", keyPath);

Failure Output:
[main] INFO net.schmizz.sshj.transport.random.JCERandom - Creating new SecureRandom.
[main] INFO net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.31.0
[main] INFO net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-OpenSSH_7.4
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:227)
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:342)
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:390)
        at com.broadcom.ear.data.Hosted.uploadFile(Hosted.java:323)
        at com.broadcom.ear.data.Hosted.uploadHostedFile(Hosted.java:205)
        at com.broadcom.ear.data.Hosted.main(Hosted.java:179)
Caused by: net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from PKCS8KeyFile{resource=[PrivateKeyFileResource] /opt/broadcom/ear/hosted/mp1/keys/105115_privateKey}in] INFO net.schmizz.sshj.transport.random.JCERandom - Creating new SecureRandom.
[main] INFO net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.31.0
[main] INFO net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-OpenSSH_7.4
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:227)
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:342)
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:390)
        at com.broadcom.ear.data.Hosted.uploadFile(Hosted.java:323)
        at com.broadcom.ear.data.Hosted.uploadHostedFile(Hosted.java:205)
        at com.broadcom.ear.data.Hosted.main(Hosted.java:179)
Caused by: net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from PKCS8KeyFile{resource=[PrivateKeyFileResource] /opt/broadcom/ear/hosted/mp1/keys/105115_privateKey}
        at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:47)
        at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62)
        at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81)
        at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68)
        at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:73)
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:221)
        ... 5 more
Caused by: java.io.IOException: Could not read key pair from: [PrivateKeyFileResource] /opt/broadcom/ear/hosted/mp1/keys/105115_privateKey
        at net.schmizz.sshj.userauth.keyprovider.PKCS8KeyFile.readKeyPair(PKCS8KeyFile.java:101)
        at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81)
        at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:45)
        ... 10 more
![105115_privateKey](https://user-images.githubusercontent.com/79106174/111328070-8b181f00-8633-11eb-92f5-a2d3dfaa2e02.gif)

**Comment by hierynomus** [comment]
Your key file is incorrectly detected as a PKCS8 file, whereas it is in PKCS5 format. 

Which version of SSHJ are you using?

**Comment by splat-man** [comment]
implementation 'com.hierynomus:sshj:0.31.0'

**Comment by splat-man** [comment]
What really confuses me is why the same cert works fine when run in a Windows environment, the only thing I can think of is that it's due to a little/big endian issue.

**Comment by splat-man** [comment]
Is there a simple tool to identify the format of the key?

**Comment by splat-man** [comment]
According to our operations team who are responsible for generating the key the format of the file is PKCS8, I'm attaching the key again to make sure it came through alright.


[105115_privateKey.txt](https://github.com/hierynomus/sshj/files/6184218/105115_privateKey.txt)

**Comment by splat-man** [comment]
I discovered an issue where the file copy to the linux box was leaving a garbage line in the file which was causing the failure.
