### ISSUE TITLE
Handshake error during connection to SFTP when using Oracle Java 1.8_291

### ISSUE THREAD

**Issue by sebastian-sadlo** [hierynomus/sshj#701]
When used with newest Oracle Java 1.8_291, sshj throws an error during handshake when connecting to SFTP server.
It seems that sshj's client proposes an empty list of ciphers when negotiating with the server.
This error was observed when we were using newest Oracle Java 1.8_291.
When we use OpenJdk or older Oracle Java 1.8_281 everything works just fine.
I post a stack trace below for details.
 
Tested with sshj versions: 0.29 and 0.31
Tested with Java versions: Oracle Java 1.8_281, Oracle Java 1.8_291, OpenJdk 1.8_292
Tested on operating systems: Ununtu 20.04, CentOS 7.x 

```
Caused by: net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [] and [chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, cast128-cbc, 3des-cbc]
        at net.schmizz.sshj.transport.Proposal.firstMatch(Proposal.java:149)
        at net.schmizz.sshj.transport.Proposal.negotiate(Proposal.java:132)
        at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:222)
        at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:370)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:517)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:203)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
```

and this is the code we use to connect to the SFTP:

```
   SSHClient ssh = new SSHClient(config);
    ...
    final char[] passphrase = ...
    ...
    ssh.addHostKeyVerifier((hostname, port, key) -> true);
    ssh.setTimeout((int) socketTimeoutInMillis);
    ssh.setConnectTimeout((int) connectionTimeoutInMillis);
    ssh.getConnection().setTimeoutMs((int) responseTimeoutInMillis);
    ssh.getTransport().setTimeoutMs((int) responseTimeoutInMillis);
    try {
      ssh.connect(sftpHost, sftpPort);
    } catch (IOException e) {
      ...
    }
```

**Comment by hierynomus** [comment]
@sebastian-sadlo Do you have bouncycastle on the classpath?
