### ISSUE TITLE
BCrypt classpath hell

### ISSUE THREAD

**Issue by mindas** [hierynomus/sshj#706]
I am experiencing a classpath hell which is related to how sshj incorporates bcrypt.

Consider sshj client code below:
```
        try (SSHClient sshClient = new SSHClient()) {
            sshClient.addHostKeyVerifier(new PromiscuousVerifier());
            KeyProvider keys = sshClient.loadKeys(settings.privateKey, settings.publicKey, PasswordUtils.createOneOff(settings.passphrase));
            sshClient.connect(settings.host, settings.port);
            sshClient.authPublickey(settings.username, keys);
```

This fails on the last line with the following exception:

```
java.lang.NoSuchMethodError: org.mindrot.jbcrypt.BCrypt.pbkdf([B[BI[B)V
 	at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.initializeCipher(OpenSSHKeyV1KeyFile.java:150)
 	at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.decryptBuffer(OpenSSHKeyV1KeyFile.java:132)
 	at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readDecodedKeyPair(OpenSSHKeyV1KeyFile.java:118)
 	at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readKeyPair(OpenSSHKeyV1KeyFile.java:85)
 	at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81)
 	at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:45)
 	at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62)
 	at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81)
 	at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68)
 	at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:73)
 	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:221)
 	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:342)
 	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:360)
```

The reason for the above failure is an explicit dependency to org.mindrot:jbcrypt:0.4 which comes from my project.
The original bcrypt does not have `pbkdf` method in `BCrypt` class hence the `NoSuchMethodError`.

I am sure this is a problem of sshj, in particular of how sshj is encapsulating bcrypt. 

The deliverable jar I'm working with, com.hieronymous:sshj:0.31.0:jar has org.mindrot.jbcrypt package which clashes with the same name in the original bcrypt jar. The correct way of encapsulating this would be to put it under a package with a different name, similar to how bouncycastle are doing -- in their case, they put their own BCrypt copy under `org.bouncycastle.crypto.generators` to avoid such clashes.

**Comment by hierynomus** [comment]
@mindas This has been fixed by the PR #717 from @exceptionfactory.
