### ISSUE TITLE
SCP File uploads stuck if the remote didn't send status code

### ISSUE THREAD

**Issue by DImuthuUpe** [hierynomus/sshj#731]
The file upload thread is stuck at SCPEngine.check method probably because the remote didn't respond with the completion status code. While these are possible due to network issues, the client might need to wait for some time and invoke a timeout with an error to the user. Please look at the thread dump

```
"TaskStateModelFactory-task_thread-6" #78 daemon prio=5 os_prio=0 cpu=39889.63ms elapsed=1726257.09s tid=0x00007f27b4073000 nid=0x23c6 in Object.wait()  [0x00007f27976f4000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.9/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@11.0.9/Object.java:328)
	at net.schmizz.sshj.connection.channel.ChannelInputStream.read(ChannelInputStream.java:103)
	- waiting to re-lock in wait() <0x0000000092ae8e60> (a net.schmizz.sshj.common.Buffer$PlainBuffer)
	at net.schmizz.sshj.connection.channel.ChannelInputStream.read(ChannelInputStream.java:86)
	- locked <0x0000000092ae8e78> (a [B)
	at net.schmizz.sshj.xfer.scp.SCPEngine.check(SCPEngine.java:60)
	at net.schmizz.sshj.xfer.scp.SCPUploadClient.sendFile(SCPUploadClient.java:100)
	at net.schmizz.sshj.xfer.scp.SCPUploadClient.process(SCPUploadClient.java:78)
	at net.schmizz.sshj.xfer.scp.SCPUploadClient.startCopy(SCPUploadClient.java:70)
	at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:50)
	- eliminated <owner is scalar replaced> (a net.schmizz.sshj.xfer.scp.SCPUploadClient)	at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:43)
	- eliminated <owner is scalar replaced> (a net.schmizz.sshj.xfer.scp.SCPUploadClient)	at net.schmizz.sshj.xfer.scp.SCPFileTransfer.upload(SCPFileTransfer.java:55)
```

**Comment by DImuthuUpe** [comment]
@hierynomus suggestion to fix this?

**Comment by jpstotz** [comment]
I also encountered this problem in version 0.35:

```
 java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait0(java.base@21.0.10/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@21.0.10/Object.java:366)
        at java.lang.Object.wait(java.base@21.0.10/Object.java:339)
        at net.schmizz.sshj.connection.channel.ChannelInputStream.read(ChannelInputStream.java:106)
        - locked <0x0000000581042318> (a net.schmizz.sshj.common.Buffer$PlainBuffer)
        at net.schmizz.sshj.connection.channel.ChannelInputStream.read(ChannelInputStream.java:86)
        - locked <0x0000000581042360> (a [B)
        at net.schmizz.sshj.xfer.scp.SCPEngine.check(SCPEngine.java:60)
        at net.schmizz.sshj.xfer.scp.SCPUploadClient.startCopy(SCPUploadClient.java:75)
        at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:54)
        - locked <0x00000005810423a0> (a net.schmizz.sshj.xfer.scp.SCPUploadClient)
        at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:47)
        - locked <0x00000005810423a0> (a net.schmizz.sshj.xfer.scp.SCPUploadClient)
```
I will upgrade to 0.40.0 however I have seen that `ChannelInputStream.read(byte[],int,int)` has not been changed since 2018, so most likely the problem is still present. 

To me it seems that the main problem is that the `wait()` call has no timeout: 

https://github.com/hierynomus/sshj/blob/15d6924ba3ffc4837cf9f84ce14377dbf014031d/src/main/java/net/schmizz/sshj/connection/channel/ChannelInputStream.java#L106-L108

@hierynomus What do you think about adding a [read] timeout parameter to `ChannelInputStream`?
