### ISSUE TITLE
Ed25519PublicKey usage error within OSGI context

### ISSUE THREAD

**Issue by FireT12** [hierynomus/sshj#771]
Hi there @hierynomus,

As part of my SSHJ usage, I'm using a Ed25519 known_host key, and while this works as expected locally, when deloyed into Karaf I am unfortunately receiving the following error:

_Caused by: java.lang.NoClassDefFoundError: net/i2p/crypto/eddsa/math/Curvenâ| 	
at com.hierynomus.sshj.signature.Ed25519PublicKey.<init>(Ed25519PublicKey.java:37)| 	
at net.schmizz.sshj.common.KeyType$6.readPubKeyFromBuffer(KeyType.java:193)| 	
at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:489)| 	
at net.schmizz.sshj.transport.verification.OpenSSHKnownHosts$EntryFactory.parseEntry(OpenSSHKnownHosts.java:266)| 	
at net.schmizz.sshj.transport.verification.OpenSSHKnownHosts.readEntries(OpenSSHKnownHosts.java:81)| 	
at net.schmizz.sshj.transport.verification.OpenSSHKnownHosts.<init>(OpenSSHKnownHosts.java:62)| 	
at net.schmizz.sshj.SSHClient.loadKnownHosts(SSHClient.java:648)_

Specifically where it invokes `spec.getParams().getCurve()`.

I can see that the build.gradle is specifying, via `"Import-Package", "!net.i2p.crypto.eddsa.math"`, an instruction to not import the package that houses that class. I know the eddsa library doesn't explicitly export the math package, so I am assuming this is why SSHJ doesn't import it, but is this a known limitation within the OSGI context?

My question is, how can I use Ed25519PublicKey in an OSGI context without importing that class? Is my only option to build a custom version of SSHJ that enables that import, assuming I have an equivalent net.i2p.eddsa build that exports that package?

Any help or direction would be really appreciated. Thank you!

**Comment by FireT12** [comment]
Closed issue, as workaround, without need of rebuilding, provided at end of issue #255.
