### ISSUE TITLE
X11 forwarding doesn't work 

### ISSUE THREAD

**Issue by 15249687908** [hierynomus/sshj#796]
X11 forwarding doesn't work in my application based on the example X11.java.
Then he reported an error

net.schmizz.sshj.transport.TransportException: Socket closed
	at net.schmizz.sshj.transport.TransportImpl.write(TransportImpl.java:426)
	at net.schmizz.sshj.connection.channel.AbstractChannel.sendChannelRequest(AbstractChannel.java:380)

**Comment by hierynomus** [comment]
Might be helpful to have a bit more information and logs. If you can provide those, I'd be happy to take a look

**Comment by 15249687908** [comment]
Thank you. I missed xlaunch, so I made a mistake
