### ISSUE TITLE
Failed to connect to higher version OpenSSL server after configuring KeepAliveInterval

### ISSUE THREAD

**Issue by 2211898719** [hierynomus/sshj#933]
`ssh.getConnection().getKeepAlive().setKeepAliveInterval(60);`

![image](https://github.com/hierynomus/sshj/assets/77563386/691683cd-0deb-4b7f-93ae-d1185b57fbe2)

`
net.schmizz.sshj.transport.TransportException: strict KEX violation: unexpected packet type 2 (seqnr 1)
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:548) ~[sshj-0.38.0.jar:na]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500) ~[sshj-0.38.0.jar:na]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113) ~[sshj-0.38.0.jar:na]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200) ~[sshj-0.38.0.jar:na]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60) ~[sshj-0.38.0.jar:na]
`

`		<dependency>
			<groupId>com.hierynomus</groupId>
			<artifactId>sshj</artifactId>
			<version>0.38.0</version>
		</dependency>
`

**Comment by 2211898719** [comment]
![image](https://github.com/hierynomus/sshj/assets/77563386/629dedc5-6c7d-47d8-9cc3-0104a71d5004)

**Comment by derklaro** [comment]
I had the same issue. Fixed by using a custom KeepAlive sender that just waits until the key exchange is completed before starting the hearbeat.

**Comment by 2211898719** [comment]
How to customize it
