### ISSUE TITLE
connection problems with terrapin mitigation

### ISSUE THREAD

**Issue by rhuddleston** [hierynomus/sshj#937]
Some clients use hosted ssh servers on files.com, when I check the server with https://github.com/RUB-NDS/Terrapin-Scanner/releases is says all is good. When I upgrade sshj to the latest version and attmpt to connect to this server I get:

net.schmizz.sshj.transport.TransportException: SSH_MSG_IGNORE not allowed during initial key exchange in strict KEX
at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:548)
at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200)

thoughts on this? One of the IP's used for reference: 34.204.250.40

I rolled back to an older version of sshj for now.

**Comment by rhuddleston** [comment]
finally able to track this down, was an issue with a keep-alive process sending `MSG_IGNORE`, moved the code that does this background process after the connection was fully created and now it works in both versions. Closing this issue
