### ISSUE TITLE
NullPointerException when trying to handle exception in notifyError

### ISSUE THREAD

**Issue by GiantPanda0090** [hierynomus/sshj#955]
Hi Team, we are seeing following NullPointerException when large amount of connection refused request due to network congestion. 

It will be nice if we can get some hint from SSHJ team to understand what can cause this. this happened when a SSHJ trying to handle a exception while the exception handle code got another exception(NullPointerException). Eventually crash the code. 

As far as we can see here, seems like SessionChannel is not initialized before notifyError was called. Therefore, the ChannelInputStream err is null. 

```
java.lang.NullPointerException: null
	at net.schmizz.sshj.connection.channel.direct.SessionChannel.notifyError(SessionChannel.java:228) ~[sshj-0.31.0.jar:0.31.0]
	at net.schmizz.sshj.common.ErrorNotifiable$Util.alertAll(ErrorNotifiable.java:35) ~[sshj-0.31.0.jar:0.31.0]
	at net.schmizz.sshj.connection.ConnectionImpl.notifyError(ConnectionImpl.java:261) ~[sshj-0.31.0.jar:0.31.0]
	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:620) ~[sshj-0.31.0.jar:0.31.0]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:66) ~[sshj-0.31.0.jar:0.31.0]
```

Each of the stack seems to related to the following code,  the problem here is the err object(ChannelInputStream for SSH STDERR) from " private final ChannelInputStream err = new ChannelInputStream(this, trans, lwin);" is Null. 
```
at net.schmizz.sshj.connection.channel.direct.SessionChannel.notifyError(SessionChannel.java:228) ~[sshj-0.31.0.jar:0.31.0]

    @Override
    public void notifyError(SSHException error) {
        err.notifyError(error); <<<<< NULL on err  is NULL
        super.notifyError(error);
    }


at net.schmizz.sshj.common.ErrorNotifiable$Util.alertAll(ErrorNotifiable.java:35) ~[sshj-0.31.0.jar:0.31.0]

        public static void alertAll(SSHException error, ErrorNotifiable... notifiables) {
            for (ErrorNotifiable notifiable : notifiables)
                notifiable.notifyError(error); 
        } 

at net.schmizz.sshj.connection.ConnectionImpl.notifyError(ConnectionImpl.java:261) ~[sshj-0.31.0.jar:0.31.0]

    @Override
    public void notifyError(SSHException error) {
        super.notifyError(error);
        synchronized (globalReqPromises) {
            ErrorDeliveryUtil.alertPromises(error, globalReqPromises);
            globalReqPromises.clear();
        }
        keepAlive.interrupt();
        ErrorNotifiable.Util.alertAll(error, channels.values()); 
        channels.clear();
    }


at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:620) ~[sshj-0.31.0.jar:0.31.0]


 public void die(Exception ex) {
        close.lock();
        try {
            if (!close.isSet()) {
                log.error("Dying because - {}", ex.getMessage(), ex);

                final SSHException causeOfDeath = SSHException.chainer.chain(ex); 

                disconnectListener.notifyDisconnect(causeOfDeath.getDisconnectReason(), causeOfDeath.getMessage());
                ErrorDeliveryUtil.alertEvents(causeOfDeath, close, serviceAccept);
                kexer.notifyError(causeOfDeath);
                getService().notifyError(causeOfDeath); 
                setService(nullService);
                { // Perhaps can send disconnect packet to server
                    final boolean didNotReceiveDisconnect = msg != Message.DISCONNECT;
                    final boolean gotRequiredInfo = causeOfDeath.getDisconnectReason() != DisconnectReason.UNKNOWN;
                    if (didNotReceiveDisconnect && gotRequiredInfo)
                        sendDisconnect(causeOfDeath.getDisconnectReason(), causeOfDeath.getMessage());
                }
                finishOff();
                close.set();
            }
        } finally {
            close.unlock();
        }
    }

at net.schmizz.sshj.transport.Reader.run(Reader.java:66) ~[sshj-0.31.0.jar:0.31.0]


    public void run() {
        try {
            final Decoder decoder = trans.getDecoder();
            final InputStream inp = trans.getConnInfo().in;
            final byte[] recvbuf = new byte[decoder.getMaxPacketLength()];
            int needed = 1;
            while (!isInterrupted()) {
                int read;
                try {
                    read = inp.read(recvbuf, 0, needed);
                } catch(SocketTimeoutException e) { 
                    if (isInterrupted()) {
                        throw e;
                    }
                    continue;
                }
                if (read == -1) {
                    throw new TransportException("Broken transport; encountered EOF");
                } else {
                    needed = decoder.received(recvbuf, read);
                }
            }
        } catch (Exception e) {
            // We are meant to shut up and draw to a close if interrupted
            if (!isInterrupted()) {
                trans.die(e); <<<<< e thrown
            }
        }
        log.debug("Stopping");
    }
```

SSHJ Version: 0.31.0 Check the master branch, relevant code has not changed

Thanks a lot for the help.

**Comment by GiantPanda0090** [comment]
Hi 

Just a suggestion, maybe better way is to check if ChannelInputStream exist before calling notify Error like the one below?

```
    @Override
    public void notifyError(SSHException error) {
    if (null != err ){
        err.notifyError(error); 
	}else{
               #Dummy error handling code. There must be a better way. 
	        err = new ChannelInputStream(this, trans, lwin);
	        err.notifyError(error); 
		}
        super.notifyError(error);
    }
```

**Comment by GiantPanda0090** [comment]
Hi

We have done more testing by adding the following code in "src/main/java/net/schmizz/sshj/connection/channel/direct/AbstractDirectChannel.java"
```
       try {
            log.error("Sleeping for 4000 sec");
            Thread.sleep(4000);
        }catch (Exception e) {
            // catching the exception
            System.out.println(e);
        }
```

right under 

```
    protected AbstractDirectChannel(Connection conn, String type, Charset remoteCharset) {
        super(conn, type, remoteCharset);

        /*
         * We expect to receive channel open confirmation/rejection and want to be able to next this packet.
         */
        conn.attach(this);
```
 to make the constructor looks like


```
    protected AbstractDirectChannel(Connection conn, String type, Charset remoteCharset) {
        super(conn, type, remoteCharset);

        /*
         * We expect to receive channel open confirmation/rejection and want to be able to next this packet.
         */
        conn.attach(this);
        
        try {
            log.error("Sleeping for 4000 sec");
            Thread.sleep(4000);
        }catch (Exception e) {
            // catching the exception
            System.out.println(e);
        }
    }
```

Than during the time of sleeping, terminate the remote SSH Agent and we can manage to reproduce the issue. Seems like the problem is the remote agent got disconnected right after the SessionChannel got added into the queue. This makes ChannelInputStream have not initialized yet before notifyerror is trying to handled the exception. 

by modify the code to the one that mentioned above solved the problem.
